### PR TITLE
Fix minor meta issue

### PR DESCRIPTION
**Pull request by SalahAdDin**
resuelve
Enable translate meta name for Page.

### CODE REVIEW

**Comment by kaedroho** [comment]
This change requires a migration, can you add one?

**Comment by SalahAdDin** [comment]
Oh, yes, need this:

```python
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0002_auto_20150812_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name_plural': 'Pages', 'verbose_name': 'Page'},
        ),
    ]
```

**Comment by SalahAdDin** [comment]
And the meta class will be necessary for core app and files app :D :+1:

**Comment by kaedroho** [comment]
Please can you add that migration to this branch?

Also, that migration depends on a migration that isn't in wagtail. Please can you change ``0002_auto_20150812_1248`` to ``0016_change_page_url_path_to_text_field``

**Comment by SalahAdDin** [comment]
I don't want put a migration file because this depend's to the other not apps, and they make this hard, sorry.

**Comment by gasman** [comment]
Completed in #1659.

**Pull request closed without merging**
