### PR TITLE
Show site name on notification messages when updating or creating sites, when available

### PR DESCRIPTION
**Pull request by chrxr**
Regarding #2092  

Not sure if this is appropriate. If site name is present then displays just site name (+ [default] if necessary). Port is excluded.

Also fixed a PEP8 issue with AND at beginning of a new line.

### CODE REVIEW

**Comment by chrxr** [comment]
Tests added. First time I've done tests, so please let me know if there's anything I could do better there.

Cheers,
Chris

**Comment by timheap** [comment]
The tests look good, @chrxr! The pep8 style checker has spotted some issues with your code though, which is the failed check in the test result block below. You can check out the details of the failed check to find out more details. You need two new lines between class definitions, but your new test class only has one new line between the classes above and below.

**Comment by chrxr** [comment]
Thanks @timheap, resubmitted.

**Comment by gasman** [comment]
Thanks! Merged in 26f5016bb513a8e6f663ffa020f242c9001fcdf6.

**Pull request closed without merging**
