### PR TITLE
Refactor API to REST framework.

### PR DESCRIPTION
**Pull request by tomchristie**
Refs. #1524.

For discussion. Demonstrates a refactoring of the API to use REST framework.

This doesn't modify any of the endpoints, and is really just a rejigging of everything to use the REST framework interfaces for filtering, pagination, serialization and rendering. I've not used any of the built-in REST framework implementations for these policies, rather just ported over the existing Wagtail ones into this structure.

There's still some scope for refinement, but should all be pretty coherent as-is.

Best way to review this would be to first look through it on a change-by-change basis, to see how I've addressed these changes incrementally.

### CODE REVIEW

**Comment by tomchristie** [comment]
Some flake8 failures to be addressed: http://drone-flake8.kaed.uk/github.com/torchbox/wagtail/rest-framework/297f64509ad6519fb2eb736f10b544869e8734af

**Comment by tomdyson** [comment]
Thanks, @tomchristie! We're really pleased to have your input on this.

**Comment by kaedroho** [comment]
Setting the charset to utf-8 fixes the tests on Python 3: https://github.com/kaedroho/wagtail/commit/f42bbaf62b7965508131518086f4996108210ebb

**Comment by tomchristie** [comment]
> Setting the charset to utf-8

That would introduce some marginally incorrect behavior, setting the charset to utf8 on the response Content-Type header (JSON is a binary format that doesn't have/specify a charset, actually it's a kinda buggy that Python 3 returns unicode objects for it at all)

The REST framework JSON renderer deals with the inconsistency explicitly... https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/renderers.py#L110

We'd probably want to do the same.

**Comment by timheap** [comment]
Excellent work!

Something to consider is optional dependencies. setuptools and pip both support optional dependencies. Setting `django-rest-api` as an optional dependency would allow people who don't need the API in their project to not install it, making install and set up quicker.

The [`setuptools` docs have more detail](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), but the quick version is to do the following in `setup.py`:

```python
setup(
    # ...
    extras_require={
        'api': ['django-rest-framework==313'],
    },
)
```

Users can then install the optional API dependencies by running `pip install wagtail[api]==1.0`, or by putting `wagtail[api]==1.0` in their requirements file.

**Comment by tomchristie** [comment]
@timheap Sure. Ran a few different installs to get a really broad idea on relative install times...

Summarizing Django, Pillow, REST framework:

    Successfully installed django-1.8.3
    real	0m9.494s
    Successfully installed pillow-2.9.0
    real	0m3.110s
    Successfully installed djangorestframework-3.1.3
    real	0m1.414s

And Wagtail complete with dependancies:

    Successfully installed wagtail-1.0
    real	0m19.614s

So I'd *assume* you'd roughly see equivalent of 19.5s ---> 21.0s install times with REST framework included.

**Comment by tomchristie** [comment]
As it stands I'm about done with this - happy to run through as many rounds of review as is helpful for you folks.

Also totally recognize that this would represent an opinionated change, so really in your hands where you want to take this.

**Comment by MechanisM** [comment]
@tomchristie thanks a lot for your contribution! I'm appreciate this! I love(and using a lot) both wagtail and drf. Now wagtail became better with drf.
P.S. remember my avatar? :smile_cat:

**Comment by tomchristie** [comment]
@MechanisM - Yup. Howdy.

**Comment by kaedroho** [comment]
This excellent work, thanks!

I'll merge this now as it doesn't break anything and is a good improvement already. We can do further refinements in later PRs.

I thought I'd have a go at replacing that ``get_api_fields`` function with REST framework serialisers (#1579). Would be nice to hear any ideas you have on that :)

**Comment by tomchristie** [comment]
Ah grand, thanks!

> I thought I'd have a go at replacing that get_api_fields function with REST framework serialisers 

Had a glance over and didn't understand things on first pass, but I'll aim to take another look.

Alternatively: feel free to ping me when you think its ready to go if you want another pair of eyes for review.

**Comment by respondcreate** [comment]
Great work @tomchristie !!

**Comment by SalahAdDin** [comment]
@tomchristie Well done man!

**Pull request merged**
