### PR TITLE
startswith first arg must be str or a tuple of str, not __proxy__

### PR DESCRIPTION
**Pull request by MechanisM**

### CODE REVIEW

**Comment by gasman** [comment]
Thanks! Can you give an example of where this is failing (and if possible, create a test case for it)?

**Comment by kaedroho** [comment]
It sounds a bit like a menu item with a lazily resolved url. Probably a custom app.

Wouldn't it be better to cast to ``six.text_type`` in case of unicode characters in the URL on Python 2?

**Comment by MechanisM** [comment]
It's wagtail-torchbox devel branch on django 1.8 and python 3.4.3 with latest wagtail aswell

**Comment by MechanisM** [comment]
After today commits issue gone!
So, I'm closing the issue.

**Pull request closed without merging**
