### PR TITLE
Improvements to "creating page models" and panels reference

### PR DESCRIPTION
**Pull request by kaedroho**
This improves the "creating page models" docs and removes some duplication with the "panels reference" docs.

### CODE REVIEW

**Comment by gasman** [comment]
I think there ought to be a link from the new section in topics/creating_pages to the panels reference page.

**Comment by kaedroho** [comment]
Thanks Tom, tweaks implemented

**Comment by kaedroho** [comment]
"Template rendering" section ready for review

**Comment by kaedroho** [comment]
Ready for review!

**Comment by gasman** [comment]
Great job! Merged with some (hopefully uncontroversial) copyediting tweaks in 7d67e4b4481528d05566dee14ec55f108c8f356a.

**Comment by kaedroho** [comment]
Cheers Matthew! :beers:

**Pull request closed without merging**
