### PR TITLE
Revisions UI (#2170 rebased)

### PR DESCRIPTION
**Pull request by gasman**
just to give it a run through CI...

### CODE REVIEW

**Comment by gasman** [comment]
Merged in 5e07bead42d35bf703bf69f47f1ddc2cbf9839ee + parents

**Comment by SalahAdDin** [comment]
But, you forgot localizate this feature:
seleccion_051
seleccion_052

My project are in Spanish and the admin is in spanish, but revisions still is english.

**Comment by heymonkeyriot** [comment]
@SalahAdDin I suspect it's because it hasn't been translated. Revisions haven't yet been translated in Italian either (https://www.transifex.com/torchbox/wagtail/translate/#it/wagtailadmin/77472003?translated=no) @gasman is a maintainer of the Transifex project and would be able to corroborate that more easily than I can.

**Comment by gasman** [comment]
@heymonkeyriot @SalahAdDin That's correct, yes. Translations can only happen after the feature has been merged, and this was one of the last features to be merged for 1.4rc1 - as a result, there was no time window before 1.4rc1 for the translations to be done. The Spanish translation *has* now been completed, and the translations will be included in the final 1.4 release.

**Comment by SalahAdDin** [comment]
Oh yeah! It's a goo news, good works :+1:

**Pull request closed without merging**
