### PR TITLE
Add docker and fig to get contributing faster

### PR DESCRIPTION
**Pull request by pvdvreede**
Hey there,

Love your work! I have been using wagtail since 0.3 and it has been great!

I wanted to help out and contribute, but I am primarily a Ruby developer so I am having trouble figuring out how to setup the repo and get all the tests running etc.

I use Docker and Fig (now docker-compose) for my dev at work, and thought it would be great to have that same setup here, so that it is really simple for people to get setup so that the barrier to contribution for non-Python devs is lower.

This is just a start, but I wanted to know your thoughts on the matter and if its of interest we can work on getting a more complete setup and perhaps multiple docker files for different python versions connected to different databases in the fig.yml.

### CODE REVIEW

**Comment by kaedroho** [comment]
+1 from me!

**Comment by tomdyson** [comment]
Thanks a lot, @pvdvreede! This looks really good. What would 'a more complete setup' look like?

**Comment by pvdvreede** [comment]
Well if this PR gets merged into docker-compose: https://github.com/docker/compose/pull/1075/files, then we could have a `Dockerfile.py2` a `Dockerfile.py3` and then in the `fig.yml` (which would be renamed to `docker-compose.yml`) we could have a `apppy2` container and a `apppy3` container, so that you could run tests with `docker-compose run apppy2 make test` and `docker-compose run apppy3 make test`. You can then extrapolate the docker containers to all connect to different databases as well if you need, and for different django versions as well.

However, we can just leave it as it is for the moment, to either use python 2.7 (as it currently is) or python 3.4 and it would just be a good start to get contributing.

The thing I would need help from you guys with is what should actually go in the Dockerfile to make sure the environment is setup correctly. Maybe I have done it correctly, and indeed the tests work and pass, but not sure if I am missing anything.

**Comment by kaedroho** [comment]
It appears that the ``.drone.yml`` file can actually do this.

If you download the drone client and run ``drone build .`` it will build a local docker container and run the tests.

**Comment by pvdvreede** [comment]
That is a good advantage @kaedroho to have the same environment as tests. Do you know if you can setup the `.drone.yml` do run a matrix of different python versions and databases as well? That would be the optimum thing if you could run one command to run all tests across all supported python versions and dbs before you push.

I know docker-compose will support the dockerfile option soon so that it will possible to do this with docker-compose. If drone can also do it, then that would be good enough for me...

**Comment by zerolab** [comment]
Matrix builds are coming to Drone, but not quite there. See https://github.com/drone/drone/issues/6

**Comment by gasman** [comment]
Setup scripts like this are very definitely welcome, but including them as an officially-supported tool within the Wagtail repo is a bit problematic. It means that we need to keep them up to date whenever our build dependencies change (such as CSS precompilation #1228, which has been added since this PR was submitted) - and since we don't enforce the use of any particular virtualisation platform, we can't count on developers having the knowledge to do that (or the means to test their changes).

I think the best way forward is for these scripts to live outside of the main repo as unofficial / semi-official packages (as I've done with my Vagrant script that serves much the same purpose as this one: https://github.com/gasman/vagrant-wagtail-develop) - and link to them from the developer documentation.

**Comment by pvdvreede** [comment]
Thats a fair call. I will close this PR and see if I can setup this stuff as a separate repo, then maybe make another PR for the doco with a link.

**Comment by antero10** [comment]
Also, instead of add the `env` vars by this way:

```
environment:
   DATABASE_NAME: wagtail
   DATABASE_USER: postgres
   DATABASE_HOST: db
```

you can use an `env` var file and add and example copy of that file. something like:

```
env_file: 
  - .env

```

and `.env` will look file like:

```
  DATABASE_NAME=wagtail
  DATABASE_USER=postgres
  DATABASE_HOST=db
```

i think looks nicer by this way. I just an idea

**Pull request closed without merging**
