### PR TITLE
Restructure the docs

### PR DESCRIPTION
**Pull request by kaedroho**
This PR does the following:
 - Moves core_components one level up
 - Renames contrib_components to contrib

This will probably break a lot of URLs (may be possible to add some redirects), but makes the docs easier to browse as subsections of the core components can now be found in the left hand menu.

### CODE REVIEW

**Comment by tomdyson** [comment]
Thanks, @kaedroho. It looks like RTD supports redirects:

http://docs.readthedocs.org/en/latest/automatic-redirects.html#redirecting-to-a-page

**Comment by kaedroho** [comment]
Thanks @tomdyson. Will have a look into that a bit later

**Comment by kaedroho** [comment]
A couple more things I'd like to do:
 - Move "Sites" somewhere else (probably "reference")
 - Move "using images in templates" out of images index (create new page for this in images section)

**Comment by kaedroho** [comment]
It looks like RTDs redirects would do the job. Theres one called a "prefix" redirect that would handle the core components change in one go (tried on another project). We would need to create one redirect for each page in the contrib section.

**Comment by kaedroho** [comment]
Actually, the redirects may be tricky as they probably apply to all versions of the docs, meaning 0.8 and before may get a bit screwed up of we create those redirects.

**Pull request merged**
