### PR TITLE
Allow defining a custom form for Page validation

### PR DESCRIPTION
**Pull request by timheap**
Developers can create their own form class, with custom validation logic, by subclassing `wagtail.wagtailadmin.forms.WagtailAdminPageForm` and setting the `MyPage.base_form_class` attribute:

```python
from wagtail.wagtailadmin.forms import WagtailAdminPageForm
from wagtail.wagtailcore.models import Page

class EventPageForm(WagtailAdminPageForm):
    def clean(self):
        cleaned_data = super(EventPageForm, self).clean()

        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        if start_date and end_date:
            if start_date < end_date:
                msg = 'Start date must be before end date'
                self.add_error('start_date', msg)
                self.add_error('start_date', msg)
            elif start_date == end_date
                cleaned_data['end_date'] = None

        return cleaned_data

class EventPage(Page):
    start_date = models.DateField()
    end_date = models.DateField()

    content_panels = Page.content_panels + [
        FieldPanel('start_date'),
        FieldPanel('end_date'),
    ]
    base_form_class = EventPageForm
```

The `Page` form validation logic has been moved to `WagtailAdminPageForm.clean()`, out of the
`wagtail.wagtailadmin.views.pages.validate_page_data()` function. There may be an issue for developers who have made their own `Page.edit_handler`, which will not set the correct form class for validating pages.

Constructing a `TabbedInterface` for `Page`s is now done by the `Page.get_edit_handler()` function, which behaves the same as the code embedded in `wagtail.wagtailadmin.views.pages.get_page_edit_handler()`. Because it is a function on `Page`, developers can easily override it site wide using a custom `Page` base class.

### CODE REVIEW

**Comment by gasman** [comment]
Excellent! This fixes #1245 and #1291, I guess...?

**Comment by timheap** [comment]
It does fix both of those issues, yep. I can split it up into multiple commits that fix each issue independently if that would help you review it?

**Comment by timheap** [comment]
Although it seems I screwed up some code and then didnt test it. Thanks, Travis!

**Comment by gasman** [comment]
> It does fix both of those issues, yep. I can split it up into multiple commits that fix each issue independently if that would help you review it?

Yes please - that would be very handy!

**Comment by prydie** [comment]
My only comment at this point would be that it would be great to see some documentation for this.

**Comment by timheap** [comment]
Documentation and tests are absolutely coming, I just wanted to get this initial work up.

**Comment by timheap** [comment]
Alright, everything has been split, and tests have been added. I've not yet written documentation. I'll hold off on that until everyone agrees that this is an approach worth taking.

**Comment by gasman** [comment]
Merged in 8afe69fd721a10107aef716c13138f2d8e92bc3b + parents - thanks!

**Comment by timheap** [comment]
Thanks! This does not have documentation yet, as I was wanting to discuss whether this was the approach everyone thought was best before writing it. I'll make a bug report about the missing docs.

**Comment by gasman** [comment]
@timheap No problem... as this change is as much about code cleanup as it is implementing new features, I figured it was well worth merging, with or without docs. Cheers!

**Comment by JaredOzzy** [comment]
How would i go about getting this done on an  Orderable? The Orderable fields aren't in the cleaned_data.

**Pull request closed without merging**
