### PR TITLE
Fix behaviour of page permission formset on groups admin

### PR DESCRIPTION
**Pull request by gasman**
Previously, clicking the 'delete' button next to a page permission entry would submit the form; this PR fixes it so that the row is deleted while the user stays on the page. Have also refactored it to not pull in more of the page editor / edit_handlers infrastructure than is strictly necessary (which means we get to ditch one of our dynamic JS templates. Yay!)

### CODE REVIEW

**Comment by tomdyson** [comment]
@kaedroho to review.

**Comment by kaedroho** [comment]
Getting an error when I delete an existing group page permission and add a new one with the same page and permission type in the same request: "Group Page Permission with this Group, Page and Permission type already exists."

**Comment by gasman** [comment]
> Getting an error when I delete an existing group page permission and add a new one with the same page and permission type in the same request: "Group Page Permission with this Group, Page and Permission type already exists."

I think this may be a Django bug - the same thing happens when editing group page permissions within Django admin (edit a group, tick the Delete checkbox against a page permission, and add a matching page permission below it - validation fails).

**Comment by kaedroho** [comment]
I'm happy for this to be merged with that issue unresolved, this is definitely a massive improvement over what we had before.

**Comment by gasman** [comment]
Confirmed that this is a general Django issue (as of Django 1.8.4) - this behaviour is shown by any ModelFormset with can_delete=True and a unique constraint on the model. Will report it once I've got my head round the full scope of the bug - I have a nasty feeling that it's a fundamental limitation of model validation (because you can only say "does this model pass validation?", not "would this model pass validation if models X, Y and Z were to be deleted?")

Meanwhile, I'll go ahead and merge this.

**Pull request merged**
