### PR TITLE
[Elasticsearch 2] Renamed search backend classes

### PR DESCRIPTION
**Pull request by kaedroho**
Suffixing them with the word ``Backend``

### CODE REVIEW

**Comment by m1kola** [comment]
It's odd. [Some of build jobs](https://travis-ci.org/torchbox/wagtail/builds/144403145) were failed. I don't think that the reason in this PR. I've rebased `cleanup/search-class-names` branch on top of `master`.

**Comment by m1kola** [comment]
I don't understand... I've pushed a copy of this branch into my fork and [the build is green](https://travis-ci.org/m1kola/wagtail/builds/144438545), but in the main repository [build fails](https://travis-ci.org/torchbox/wagtail/builds/144442819) (again!).

It looks like Travis tries to build c30f9c6c18e370852ee8246e10b34641ea63d7ad commit, but I have not idea why: there is no such commit in this branch!

**Comment by m1kola** [comment]
Rebased on top of `master` (#2567, #2568 were merged into `master`).

**Comment by kaedroho** [comment]
Rebased on master

**Comment by kaedroho** [comment]
@m1kola 
Looks like the tests are fixed now. Are you happy with the deprecation warnings?

**Comment by m1kola** [comment]
@kaedroho yep, I think we can merge this PR ;)

**Comment by kaedroho** [comment]
Thanks @m1kola!

**Pull request merged**
