### PR TITLE
Replacing bitter with Roboto Slab, updating opensans

### PR DESCRIPTION
**Pull request by davecranwell**
Fixes https://github.com/torchbox/wagtail/issues/1248

Our version of OpenSans previously only contains the basic Latin subset, so this adds all the other subsets it is available in. 

Bitter however has no more subsetting to enable and only comes in Latin. Bitter has therefore been replaced with Roboto Slab. 

It's used for a) the stats blocks on the dashboard, b) rich text fields and title fields in the page editor interface.

### CODE REVIEW

**Comment by davecranwell** [comment]
@tomdyson suggests we have two bundlings of our fonts: 1. latin only, 2. everything, then toggle which set is loaded based on some kind of django setting.

At present the total WOFF download, without gzip, without Bitter, but included all subsetting, is ~800k. This could be reduced to ~400k with the removal of the italic version, which is desirable but isn't that much of an improvement on the browser's attempt at italicising the regular font.

With only the latin subset enabled, in the same conditions, the total WOFF download is more like 100k and would be much more desirable for users who knew their site would never use non-latin characters.

With server gzipping enabled I'd expect even the fully subset version to be too small to worry about.

**Comment by timheap** [comment]
I think a config option to save ~400K is not worth the bother. Even though all our clients are native english speakers making english content for english speaking readers doesn't mean they won't include some non-latin characters - for example the names of non-english people or places could easily be used on an otherwise completely english site.

**Comment by davecranwell** [comment]
In the interest of getting something shipped, perhaps a better solution here would be to fix the lack of extended character support in Open Sans and consider Bitter separately. Clearly we can't continue to use Bitter, but do we really want to replace it with something which will add another unavoidable 400k of subsetting?

**Comment by gasman** [comment]
Merged in e08e35d470dc836ee9753eba5e67a0cf6ce46b9a + parents.

**Pull request closed without merging**
