### PR TITLE
Limit logo animation CSS so that custom logos don't nod

### PR DESCRIPTION
**Pull request by gasman**
as per https://github.com/torchbox/wagtail/pull/1979#issuecomment-161603586

### CODE REVIEW

**Comment by davecranwell** [comment]
I think our preferred specificity order is `class.class:pseudo-class` so please can it be  img.wagtail-logo:hover`. Other than that, fine.

**Comment by gasman** [comment]
Merged with order tweaked in ad7596a96daf8a3fb4dbaeb387aa9bc4a0667be8.

**Comment by MechanisM** [comment]
I think that wagtail bird should wag the tail instead of doing a nod =)

**Comment by tomdyson** [comment]
I agree! Who knows about SVG animation?

**Comment by davecranwell** [comment]
Something like this? http://codepen.io/davecranwell/pen/obgXaL

**Comment by MechanisM** [comment]
@davecranwell yeah!

**Comment by timorieber** [comment]
Nice idea!

**Pull request closed without merging**
