### PR TITLE
Removed filters cache on {% image %} tag

### LINKED ISSUE #541: Mysql Support
Hi guys

Matt here from the University of Southwales.

I did mention I was going to harass you about allowing us to use Mysql, so here I am, harassing you about letting us use Mysql.

I realise there is this issue, but it's not exactly what I wanted to do, that being harass you about allowing us to use mysql

https://github.com/torchbox/wagtail/issues/215

I've just started using pgadmin3, and its totally alien to me :-(

I'm sure there'd be others who would like to use mysql as well.

Regards

Matt

### LINKED ISSUE #865: image tag runs query on template load
Theres a database query in the ``__init__`` method of ``ImageNode``:

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/templatetags/wagtailimages_tags.py#L42

This causes a query to be generated every time the template is loaded. The filter is not actually needed until the node renders though.

This can cause crashes if you are trying to load a template without a database (such as doing offline compression of assets).

### PR DESCRIPTION
**Pull request by kaedroho**
Keeping filter objects globally seems to upset mysql. Also, performing querys in the ``__init__`` method of a template node causes queries to be made even if the template isn't being fully rendered (eg. compressing static files)

This may hit performance slightly as it removes a bit of caching.

Fixes #541
Fixes #865

### CODE REVIEW

**Comment by kaedroho** [comment]
Ok, this fixes the crash in the tests on MySQL. But MySQL is still "going away" on teardown.

**Comment by gasman** [comment]
Thanks for looking into this. I'd really like to get to the bottom of why this error occurs, to be sure that we aren't just sweeping a more serious issue under the carpet by making this change. Perhaps it's because running the filter query up-front causes a lot of get_or_create lookups in close succession, leading to a race condition? (Even so, that explanation doesn't quite add up: surely any race conditions within get_or_create were addressed by Django ages ago; and even if those lookups happen in close succession, I wouldn't expect them to happen in parallel, at least not during tests.)

**Comment by zerolab** [comment]
I did a quick search around. It is likely that the MySQL connection is not being closed, so the thread waits until it gets a timeout.

Piwik try to fix it by tweaking the wait_timeout and max_allowed_packet vars. See https://github.com/piwik/piwik/pull/6963/files

Throwing this into the mix, could be useful.

**Comment by kaedroho** [comment]
Thanks @zerolab giving that a try now...

Me and @gasman just had a chat and decided it would be best to turn ``Filter`` into a standard python class instead of a Django model. This would remove the need to lookup the ``Filter`` object from the database in the first place.

**Comment by kaedroho** [comment]
Seems to have worked, thanks!

**Comment by gasman** [comment]
Closing in favour of #1110. (ping @salvadormrf, as it looks like you've already merged this one into your fork)

**Pull request closed without merging**
