### PR TITLE
Document `site_name` attribute of Site

### LINKED ISSUE #2099: Model reference docs for sites need an update
As spotted by @SalahAdDin and @kaedroho after merging #1814 the new ``site_name`` field for sites needs to be documented in http://docs.wagtail.io/en/v1.3/reference/pages/model_reference.html#id1.

### PR DESCRIPTION
**Pull request by gasman**
fixes #2099

### CODE REVIEW

**Comment by kaedroho** [comment]
This looks good, thanks!

I think that having both the ``site_name`` field and ``WAGTAIL_SITE_NAME`` setting is a little confusing as the naming suggests they're the same thing.

I remember we've discussed in the past putting settings such as site name, hostname, etc in the django settings. Is there still a plan to do that?

**Comment by davecranwell** [comment]
Renaming `WAGTAIL_SITE_NAME` to `INSTALLATION_NAME`/ `ADMIN_TITLE` / `WELCOME_TITLE` or similar seems desirable.

**Comment by alexfromvl** [comment]
I used the {{ site.site_name }} and {{ self.site_name }}, but it does not work.
Given all the changes the site name, how to call "Site_name" in a page template?

**Comment by gasman** [comment]
Hi @alexfromvl - please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.

**Pull request merged**
