### PR TITLE
Add button class to all inputs. Fixes #2512

### LINKED ISSUE #2512: Broken styles for some buttons on dashboard
**Steps to reproduce:**
1. Open any page and make some changes
2. Submit the page for moderation
3. Go to the dashboard
3. Put cursor on a title of the page in "pages awaiting moderation" section

**Result:**
screen shot 2016-04-25 at 17 55 23

**Expected result:**
screen shot 2016-04-25 at 18 03 28

### PR DESCRIPTION
**Pull request by JoshBarr**
Adds button class to all inputs, thereby removing the need for attribute selectors, and ensuring `.button` class and any modifiers work appropriately.

Fixes #2512.

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @JoshBarr! I see a lot of buttons on the styleguide page have lost their styling now - I guess they just need the `button` class adding too?

(I guess this change is going to affect a lot of third-party Wagtail add-ons. Probably a necessary evil, though... :-/ )

**Comment by JoshBarr** [comment]
Yeah it's probably something we need to communicate clearly in the release notes for 1.5... I couldn't come up with a non-hacky way of fixing that specificity issue. We're going to run into these visual regressions across third party modules if we touch/refactor any of the CSS. Which means we're a little bit limited with how much we can improve this part of the project without creating lots of work for existing devs. 

Using an abstraction, like `{% include 'button.html' with type='submit' style='primary' attrs='{"foo":"bar"}'  %}` could help? There's plenty of repeated code in Wagtail's templates that could be DRYed up. 

We could then possibly PR against all the popular open source modules to make it a bit less painful for the community?

**Comment by gasman** [comment]
@JoshBarr I agree, an abstraction for buttons would really help here. @jonnyscholes came up with a nice approach for this in #1435 that we should really bring back up to date!

**Comment by gasman** [comment]
Merged (with upgrade consideration note added) in 91e81d6bc04eccc5dbcf1d760a9ebd912e6879a8 + parents.

**Pull request closed without merging**
