### PR TITLE
Documented the settings variable for WAGTAIL_USAGE_COUNT_ENABLED

### LINKED ISSUE #1723: Docs required for WAGTAIL_USAGE_COUNT_ENABLED

### PR DESCRIPTION
**Pull request by jjanssen**
Fixes #1723

### CODE REVIEW

**Comment by m1kola** [comment]
Thanks @jjanssen!

If I'm not mistaken counter doesn't show images that were used in rich text editor or in stream field. How do you think, it's worth mentioning?

**Comment by jjanssen** [comment]
Thanks for the feedback @m1kola . I think it's worth mentioning in a note just beneath the description. I'll look into it and send an update with the note.

**Comment by gasman** [comment]
Thanks!

**Comment by ghostwords** [comment]
Last I checked, this counter also doesn't take usage by snippets into account, although I think it should. Snippets could be a major component of your Wagtail site; for example, `Student` models are snippets that have foreign keys to profile photos but those photos appear to be unused in the image browser UI.

**Pull request merged**
