### PR TITLE
Branding logo userbar

### PR DESCRIPTION
**Pull request by Luperi**
Introduced the possibility to customize the default wagtail logo in userbar

### CODE REVIEW

**Comment by gasman** [comment]
Thanks! Please can you create this as a new branch based on `torchbox/master`? At the moment this is mixed in with your page privacy PR.

**Comment by Luperi** [comment]
Ok @gasman , and I'll commit into torchbox:stable/1.4 or 1.3? Thanks

**Comment by gasman** [comment]
Submit it to torchbox:master please - the stable branches are no longer receiving new features.

**Comment by Luperi** [comment]
@gasman It would have been better to do the same thing with my other pull-request #2321 ?

**Comment by gasman** [comment]
Yes, but don't worry about that too much - I'll perform the merge manually, so I'll select the appropriate branch at that point.

**Comment by Luperi** [comment]
@gasman recreated both of the pull requests. Submitted them to torchbox:master :D

**Pull request closed without merging**
