### PR TITLE
Update trying_wagtail.rst

### PR DESCRIPTION
**Pull request by angadgill**
Minor change to the Demo setup instructions. The VirtualBox GUI needs to be up and running for the commands to work.

### CODE REVIEW

**Comment by gasman** [comment]
Hi @angadgill,
These commands should be entered on the command line - there's no need to use the VirtualBox GUI.

**Comment by angadgill** [comment]
Hey @gasman,

Yes, but when I tried to run the commands I got an error that basically said, "VirtualBox GUI should be open when running these commands." So I opened up VirtualBox and then the commands ran just fine. Have you ever faced this issue? I'm trying to reproduce it now.

I guess I should have modified the text to say "open VirtualBox GUI, and run the following in a command line"

Thanks!
Angad

**Comment by gasman** [comment]
I haven't encountered anything like that, no - although I haven't upgraded Vagrant for a while, so it might be something that's specific to newer versions. Let me know the exact error message, and I'll investigate further.

**Comment by angadgill** [comment]
@gasman, I haven't been able to reproduce this. Please consider this closed. 

Thanks.

**Pull request closed without merging**
