### PR TITLE
Fix Error serving documents with Django Cache Middleware enabled [#983]

### LINKED ISSUE #983: Error serving documents with Django Cache Middleware enabled
I get an error each time I serve an uploaded document (pdf file) and my Django cache middleware is enabled. I'm using Redis as a cache backend, probably happens with any backend but I'm not sure. Some of the details are:
```
Django Version:	1.7.1
Exception Type:	TypeError
Exception Value:	
can't pickle instancemethod objects
Exception Location:	/var/www/bcito/venvs/test.com/lib/python2.7/copy_reg.py in _reduce_ex, line 70
Python Executable:	/usr/bin/uwsgi-core
Python Version:	2.7.6
```

I've found a workaround editing the way I include the wagtaildocs urls.py in my app. I make use of the *never_cache* decorator. Instead of having:

```
urlpatterns = patterns(
    ...
    url(r'^documents/', include(wagtaildocs_urls)),
    ...
```

Have this:

```
...
from wagtail.wagtaildocs.views import serve
...
urlpatterns = patterns(
    ...
    url(r'^documents/(\d+)/(.*)$', never_cache(serve.serve), name='wagtaildocs_serve'),
    ...

```

Cheers,
Jordi

### PR DESCRIPTION
**Pull request by zerolab**
Changes to fix #983:

- changed the import to `from wsgiref.util import FileWrapper`
- updated the view to return a `StreamingHttpResponse`

### CODE REVIEW

**Comment by kaedroho** [comment]
There appears to not be any tests for the docs serve view. I'll quickly add some

**Comment by zerolab** [comment]
@kaedroho good catch. On a related note, I spoke with @gasman who was not sure there was a good way to test this particular issue.

**Comment by kaedroho** [comment]
It's probably possible by running a test with the cache middleware enabled. But I think just checking that the response is streaming is enough as Django would never cache those.

**Comment by zerolab** [comment]
Should I close this in favor of #991?

**Comment by gasman** [comment]
@kaedroho Yep, that's a fair point... as a unit test, the thing we really care about is "the response correctly identifies itself as a streaming one to any middlewares that might care about that fact", not "the cache middleware doesn't crash" - so adding `AssertTrue(response.streaming)` (which is the flag that cache middleware actually checks for) should do it.

**Comment by kaedroho** [comment]
@zerolab 
If you merge #991, this ticket should automatically mark itself as merged as well.

**Pull request merged**
