### PR TITLE
Include all WSGI-mandated headers in Page.dummy_request

### LINKED ISSUE #2989: Django 1.10.1 + Wagtail 1.6.2 + django-debug-toolbar 1.5 = KeyError: 'wsgi.multiprocess'
I'm using Django 1.10.1 + Wagtail 1.6.2 + django-debug-toolbar 1.5. And **when I click "Preview" button** in admin interface, I get following error:

```
[ERROR] [django.request] [exception/handle_uncaught_exception] Internal Server Error: /cmspnl/pages/53/edit/preview/
Traceback (most recent call last):
  File "virtualenv\lib\site-packages\django\core\handlers\base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "virtualenv\lib\site-packages\debug_toolbar\middleware.py", line 122, in process_response
    bits[-2] += toolbar.render_toolbar()
  File "virtualenv\lib\site-packages\debug_toolbar\toolbar.py", line 60, in render_toolbar
    if not self.should_render_panels():
  File "virtualenv\lib\site-packages\debug_toolbar\toolbar.py", line 81, in should_render_panels
    render_panels = self.request.META['wsgi.multiprocess']
KeyError: 'wsgi.multiprocess'
```

On other pages (which are also build in Wagtail, but accessed not via preview form) - all works fine. Also on Django 1.9 + Wagtail 1.5 + django-debug-toolbar 1.5 = all works fine too.

I think this issue is Wagtail-related.

I found this problem is related to code:

```python
    def should_render_panels(self):
        render_panels = self.config['RENDER_PANELS']
        if render_panels is None:
            render_panels = self.request.META['wsgi.multiprocess']
        return render_panels
```

I've tried set `RENDER_PANELS` - but after this two Django-Toolbar panels are shown.

### PR DESCRIPTION
**Pull request by gasman**
As specified by https://www.python.org/dev/peps/pep-3333/#environ-variables . Fixes #2989 (restores compatibility with django-debug-toolbar 1.5)

### CODE REVIEW

**Comment by m1kola** [comment]
Merged:
* `stable/1.6.x` - 0bd07e176dc403cb1ce9e1fd93e5512b9431f4a1...760bba936b5ba9337fc885f4fd581325104e947a
* `master` - 89f4699a91193d34efa7435e240b4e0e3d5a9e90...b1d10db7f290a68ae5e78834677b8f238454447d

Thanks Matthew!

**Comment by SalahAdDin** [comment]
I still have the problem, debug toolbar panels doesn't works.

I have this packages:
django-debug-toolbar (1.6)
wagtail (1.7rc1)

I have this log in bash:
```bash
Not Found: /__debug__/render_panel/
[12/Oct/2016 02:48:13] "GET /__debug__/render_panel/?store_id=21e7958e15f941848532c9c130a545f6&panel_id=RequestPanel HTTP/1.1" 404 873
Not Found: /__debug__/render_panel/
[12/Oct/2016 02:48:16] "GET /__debug__/render_panel/?store_id=21e7958e15f941848532c9c130a545f6&panel_id=VersionsPanel HTTP/1.1" 404 875
Not Found: /__debug__/render_panel/
[12/Oct/2016 02:48:22] "GET /__debug__/render_panel/?store_id=21e7958e15f941848532c9c130a545f6&panel_id=VersionsPanel HTTP/1.1" 404 875
Not Found: /__debug__/render_panel/
[12/Oct/2016 02:56:35] "GET /__debug__/render_panel/?store_id=21e7958e15f941848532c9c130a545f6&panel_id=TimerPanel HTTP/1.1" 404 875
```

**Comment by tomdyson** [comment]
I don't think your problem is related to this PR. Have you checked the order of your URLs and middleware?

- https://github.com/jazzband/django-debug-toolbar/issues/568
- http://django-debug-toolbar.readthedocs.io/en/latest/installation.html#middleware

**Comment by SalahAdDin** [comment]
And no, i have my urls properly configurated, same with middleware. So, i don't know what's my problem.

**Pull request closed without merging**
