### PR TITLE
Removed all mixins that provide vendor prefixes, instead relying on autoprefixer

### PR DESCRIPTION
**Pull request by davecranwell**
Autoprefixer has been installed since the move to gulp, but our code still needlessly relied on mixins to perform the same role. This PR removes those mixins along with several others which were redundant. 

Addresses #1948

### CODE REVIEW

**Comment by gasman** [comment]
@davecranwell The changes look good to me, but when I run this locally I can't see any evidence that gulp-autoprefixer is actually doing anything. For example, I'm assuming that you've removed the `-moz-box-sizing: border-box;` lines from wagtailadmin/scss/components/datetimepicker.scss on the basis that gulp-autoprefixer is expected to add that automatically - but when I check the `.xdsoft_datetimepicker` rule in static/wagtailadmin/css/core.css, only the unprefixed `box-sizing: border-box;` line is there. Am I missing something?

**Comment by davecranwell** [comment]
Nope, you're not missing anything - box sizing is just a bad example to test since it has been supported natively by all the browsers we support, and no prefixing is necessary: http://caniuse.com/#search=box-size

A better test is `transform`, which required prefixing in IE9 and Safari: http://caniuse.com/#search=transform

**Comment by gasman** [comment]
Ah yep, cheers. Can confirm that this line https://github.com/torchbox/wagtail/pull/1964/files#diff-72f8eaf1811bb083c7d10794628b390eR434 is successfully being rewritten to

    -webkit-transform: none;
    -ms-transform: none;
    transform: none;

**Comment by gasman** [comment]
Merged in eaeb589ebb8255a53471d27e02efdaf3ae38a564 + parents

**Pull request closed without merging**
