### PR TITLE
Conform JavaScript to Airbnb StyleGuide

### PR DESCRIPTION
**Pull request by JoshBarr**
@davecranwell Hey I somewhat broke my other PR with the JS styleguide in it, so I've re-worked it into a new one. This version also ignores all the modal JS, since that's generated server-side and I had trouble getting it to pass the validator with template tags in it.

Should be all good to merge too!

### CODE REVIEW

**Comment by davecranwell** [comment]
Thanks @JoshBarr Is there any documentation of this process you can add to this PR?

**Comment by JoshBarr** [comment]
Some docs are a good idea. I'll add a JS section to the contributing page. 

In essence, it adds two tasks to the package.json:

```bash
npm run lint:js
npm run format:js
```

`npm run lint:js` will lint all the JS in the wagtail project, excluding vendor files and server-side generated files

`npm run format:js` will perform safe edits to conform your JS code to the styleguide. It won't touch the line-length, or convert quotemarks from double to single, so there's some manual intervention required to format those. 

Under the hood, the tasks use the [JavaScript Code Style (JSCS)](http://jscs.info/) library.

To edit the settings for ignored files, or to change the linting rules, edit the `.jscsrc` file in the `wagtail` project root. 

A complete list of the possible linting rules can be found here: [JSCS Rules](http://jscs.info/rules.html)

**Comment by tomdyson** [comment]
Thanks a lot, @JoshBarr!

**Comment by JoshBarr** [comment]
Happy to help @tomdyson! I used @timheap's package.json as the basis for this one, so hopefully the CSS PR comes through without too much fuss as well. Fun times on the frontend!

**Pull request merged**
