### PR TITLE
Implemented search interface for snippets

### PR DESCRIPTION
**Pull request by kaedroho**
This PR adds a search interface into the listings and chooser for snippets whose model inherits from ``wagtail.wagtailsearch.index.Indexed``.

All the choosers in Wagtail have been implemented slightly differently, this PR has some refactoring to make the snippets chooser a little more like the documents chooser.

### CODE REVIEW

**Comment by gasman** [comment]
Within the snippet chooser, the search box always appears, even for non-searchable snippets (but the search always returns the full list of snippets). This should presumably be hidden based on `is_searchable`.

**Comment by gasman** [comment]
Other than the above quibbles, :+1:

**Comment by SalahAdDin** [comment]
:+1:

**Comment by kaedroho** [comment]
Thanks @gasman both issues fixed.

**Comment by gasman** [comment]
Sorry, just found another one - pagination links on the chooser don't work for non-searchable snippets (they just get left as undecorated '#' links).

Also, the pagination count fix needs to be applied to snippets/results.html as well as chooser/results.html.

**Comment by kaedroho** [comment]
@gasman issues fixed

**Pull request merged**
