### PR TITLE
Page privacy groups

### PR DESCRIPTION
**Pull request by smakinson**
Here is a take on how restricting pages to users in specific groups could work. This builds on the same flow that was already in place for page restrictions and adds a groups option to the PageViewRestriction model. The login process uses the normal django auth. Please take a look and let me know what you think and if I missed anything. Thanks!

### CODE REVIEW

**Comment by tomdyson** [comment]
This looks great, @smakinson! Thanks a lot. We'll review ASAP.

**Comment by davecranwell** [comment]
Nice one! No issues from me with the UI.

**Comment by gasman** [comment]
Rebased here, along with some minor fixes: https://github.com/gasman/wagtail/tree/smakinson-page-privacy-groups

A couple of remaining issues to clear up:

* https://github.com/gasman/wagtail/blob/smakinson-page-privacy-groups/wagtail/wagtailcore/wagtail_hooks.py#L28

        # Super users can browse the site in full. TODO: Is this what we want?

    Yes, I think so. (Any objections...?)

* Currently, a user who has successfully authenticated but has insufficient permission for a page, is redirected back to the login page, with no message to indicate what's happened. Not entirely sure what the best approach for this is - adding a new template specifically for a "you are authenticated but don't have permission" message seems a bit heavyweight, but any alternative methods (e.g. sticking an error message in the 'messages' dict before redirecting back to the login view) would probably involve extra assumptions on how the site's login system is set up.
* Providing our own `registration/login.html` template is probably a bit too disruptive for existing users, as it's likely to override any existing login template (since standard practice is to put Wagtail's apps at the top of INSTALLED_APPS). Ideally, we want a solution that works for new Wagtail sites out of the box, but also gets out of the way as soon as the developer implements their own auth views (and still works properly regardless of how complex or non-standard those views are). Maybe adding a default login template to the 'wagtail start' project template is the answer... needs more thought, though.

**Comment by gasman** [comment]
I've posted an update on the current state of this feature at https://github.com/torchbox/wagtail/issues/257#issuecomment-248401768 - since we have several issues and PRs open about this feature, I suggest that any further discussion (unless it specifically relates to the code in this PR) is continued there.

**Comment by gasman** [comment]
Now incorporated into #3071.

**Pull request closed without merging**
