### PR TITLE
Cleaned up page validation

### LINKED ISSUE #1216: Too long url_path causes crash
The slug isn't being validated properly at the form level. When users add a too long slug, everything crashes as this slug gets sent to the database without being checked first.

PR will follow shortly...

### PR DESCRIPTION
**Pull request by kaedroho**
Previously, we added an extra validation rule to the slug field by overriding the clean_slug method on the page, which was a little hacky I think.

This PR removes this code and uses form.add_error instead (added in Django 1.7) for performing the extra validation rules.

### CODE REVIEW

**Comment by gasman** [comment]
If this is going to be merged into 0.8.x, it can't use `form.add_error` because 0.8.x still supports Django 1.6.

**Comment by kaedroho** [comment]
Could this be merged into master with form.add_error then tweaked for 0.8.x?

**Comment by gasman** [comment]
I've worked out an approach which will hopefully allow us to move the validators out of views/pages.py completely, and work on Django 1.6 too, without any radical code changes - first step is here: https://github.com/gasman/wagtail/commit/b8711ff8b42f0c2e81d56d816ee31479a7fba473

However, I've just noticed that the test in 452a0cdc44b3f46825af1fd17167cb77fff5dfb1 doesn't actually fail on latest master or stable/0.8.x - it returns 'unexpected success'. Please can you provide a revised failing test?

**Comment by kaedroho** [comment]
Doesn't appear to break on 0.8.x (no idea why).

**Comment by gasman** [comment]
As per https://github.com/torchbox/wagtail/issues/1216#issuecomment-97111915 , this problem was mis-diagnosed - the problem is with the `url_path` field, not the slug validation. Closing as invalid (but will open a separate non-priority ticket to clean up the validation as per https://github.com/gasman/wagtail/commit/b8711ff8b42f0c2e81d56d816ee31479a7fba473)

**Comment by kaedroho** [comment]
@gasman 

https://github.com/kaedroho/wagtail/commit/452a0cdc44b3f46825af1fd17167cb77fff5dfb1 failed and https://github.com/kaedroho/wagtail/commit/645c2ccf1558e8bf35e9965de8e54ce8874dba19 fixed it. So surely something is being fixed by this PR?

Also, this removes some horrible code so why not merge it as at least a cleanup?

**Comment by gasman** [comment]
As mentioned above, 452a0cdc44b3f46825af1fd17167cb77fff5dfb1 does not fail - the test returns "unexpected success". Have just confirmed this by cherry-picking on latest master.

I'd prefer to move these validators out of the view module entirely as per #1245, but I agree that this is an improvement over the current code (and the validation logic is well-covered by tests, so there's not much risk of breaking things with the change). Please rebase with a more accurate commit message, and I'll merge.

**Comment by kaedroho** [comment]
Ohh, having just retried it, I found that my test wasn't breaking. Sorry about that. I'll rebase this.

**Comment by kaedroho** [comment]
Ready for another look

**Pull request merged**
