### PR TITLE
Minor German-language snippets translation wording fix

### PR DESCRIPTION
**Pull request by raphaelstolt**
Some minor wording fixes and resolution of different snippet translations (i.e. Schnipsel vs Snippet).

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @raphaelstolt! Please can you submit these changes through https://www.transifex.com/torchbox/wagtail/ , so that they're kept in sync with other translation updates?

**Comment by raphaelstolt** [comment]
Hallo @gasman. Who can accept me as a member of the German translation team?

**Comment by gasman** [comment]
@raphaelstolt Have sent you an invitation.

**Comment by raphaelstolt** [comment]
Submitted changes into transifex.

**Pull request closed without merging**
