### PR TITLE
Minor feature: Branding favicon.

### PR DESCRIPTION
**Pull request by SalahAdDin**
Guys, i don't know where add a small suggestion, a feature, branding favicon, now i'm using brandins welcome message for do this, override de block extra_css with all code, like this:
```
{% overextends "wagtailadmin/home.html" %}
{% load i18n static compress %}
{% block extra_css %}
    {% compress css %}
        <link rel="stylesheet" href="{{ STATIC_URL }}wagtailadmin/scss/layouts/home.scss" type="text/x-scss" />
    {% endcompress %}
    <link rel="icon" href="{% static 'app/images/favicon.ico' %}" type="image/x-icon; charset=binary"/>
{% endblock %}
```

But, i think that will be better put a branding block for custom favicon :D

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Thanks man, i think that many people very apreciate this :D

**Comment by gasman** [comment]
I've just received a suggestion that we should use the Wagtail favicon from https://github.com/torchbox/wagtaildemo/blob/master/demo/static/demo/images/favicon.ico as the default here. (I'll add that when we merge this...)

**Comment by SalahAdDin** [comment]
This need a very good review, yesterday i was deploying and wagtail problem in the server and i had many problems with django compressor, the most important happens because i over extends the base.html from wagtailadmin and compressor had many conflicts with this, then, compressor don't compile all css wagtail statics and crash the web.

I think that will be very good feature but i think know that isn't easy do it.
Thank you very much guys.

**Comment by SalahAdDin** [comment]
Guys, i find the next error when i deploy my project, i change the favicon template, because the before bug, and now when i enter in admin login the server report me this issue:

```bash
Referrer: http://www.cccolomboturca.co/admin/login/?next=/admin/
Requested URL: /favicon.ico
User agent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
IP address: 127.0.0.1
```

This doesn't happen when i enter in django-admin's login, only when i enter in the wagtail-admin's login.

Thanks.

**Comment by gasman** [comment]
Added in a86b08a62214e1ff7bc7448b9cb3f31a17774bfd. There is a known issue with django-overextends and django-compressor, which should be fixed in the next release of django-compressor (https://github.com/django-compressor/django-compressor/pull/670), so it's not something to worry about here. Thanks!

**Comment by SalahAdDin** [comment]
Thank you very much man! You are awesome guys.

**Pull request closed without merging**
