### PR TITLE
Fall back on ASCII when unicode document filenames fail - fixes #1166

### LINKED ISSUE #1166: Unicode name of documents raises error
Hello,

I uploaded a file which name is in unicode (Arabic).

And when I click the link to see the file it raises an error. Here's the traceback:

 Environment:

Request Method: GET
Request URL: http://0.0.0.0:8000/documents/1/docs%D8%A7%D9%84%D9%83%D8%A7%D8%AA%D8%AF%D8%B1%D8%A7%D9%8A%D9%8A%D8%A9_%D9%88%D8%A7%D9%84%D8%B3%D9%88%D9%82.pdf

Django Version: 1.7.1
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'compressor',
 'taggit',
 'modelcluster',
 'django.contrib.admin',
 'wagtail.wagtailcore',
 'wagtail.wagtailadmin',
 'wagtail.wagtaildocs',
 'wagtail.wagtailsnippets',
 'wagtail.wagtailusers',
 'wagtail.wagtailimages',
 'wagtail.wagtailembeds',
 'wagtail.wagtailsearch',
 'wagtail.wagtailredirects',
 'wagtail.wagtailforms',
 'wagtail.wagtailsites',
 'demo')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'wagtail.wagtailcore.middleware.SiteMiddleware',
 'wagtail.wagtailredirects.middleware.RedirectMiddleware')

Traceback:
File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/wagtail/wagtaildocs/views/serve.py" in serve
  15.     response['Content-Disposition'] = 'attachment; filename=%s' % doc.filename
File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/http/response.py" in __setitem__
  177.         value = self._convert_to_charset(value, 'latin-1', mime_encode=True)
File "/home/vagrant/.virtualenvs/wagtaildemo/local/lib/python2.7/site-packages/django/http/response.py" in _convert_to_charset
  172.             raise BadHeaderError("Header values can't contain newlines (got %r)" % value)

Exception Type: BadHeaderError at /documents/1/docsالكاتدرايية_والسوق.pdf
Exception Value: Header values can't contain newlines (got '=?utf-8?b?YXR0YWNobWVudDsgZmlsZW5hbWU9ZG9jc9in2YTZg9in2KrYr9ix2KfZitmK2Klf?=\n =?utf-8?b?2YjYp9mE2LPZiNmCLnBkZg==?=')

### PR DESCRIPTION
**Pull request by gasman**

### CODE REVIEW

**Comment by gasman** [comment]
Test is currently failing on Drone because it doesn't like creating a file with a non-ASCII filename - that probably means the system locale on the Drone VM needs to be updated to something Unicode-compliant.

**Comment by zerolab** [comment]
This looks good overall. Ran the tests locally + manually tested with the example from #1166. 

The only thing is that `docsالكاتدرايية_والسوق.pdf` is served as `docslktdryy@_wlswq.txt`. Should it not retain the original name?

**Comment by gasman** [comment]
Ideally it would, yes (and it does, on Django 1.8, and I *think* earlier versions of Django with Python 3) - but that fails on Django <1.8 due to the underlying Python bug, hence the need for the workaround.

**Comment by zerolab** [comment]
Makes sense.

We could look at adding `filename*=UTF-8''%D8%A7%D9%84%D9%83%D8%A7%D8%AA%D8%AF%D8%B1%D8%A7%D9%8A%D9%8A%D8%A9_%D9%88%D8%A7%D9%84%D8%B3%D9%88%D9%82.txt` in addition to the regular filename if this becomes an issue. See http://greenbytes.de/tech/tc2231/#attwithfn2231utf8comp.

**Pull request merged**
