### PR TITLE
Allow filters in the {% image %} image variable

### PR DESCRIPTION
**Pull request by timheap**
Now it is possible to do something like:

    {% image primary_img|default:secondary_img width-500 %}

### CODE REVIEW

**Comment by kaedroho** [comment]
Thanks @timheap! I think we should add this to the docs as well

**Comment by timheap** [comment]
@kaedroho Can do, but is it really required? Being able to use filters on variables is the standard, expected behaviour in template tags in my opinion. That the image filter did not support it out of the box was surprising to me.

**Comment by kaedroho** [comment]
@timheap Ok then, I agree with that. Happy for this to be merged

**Comment by tomdyson** [comment]
Thanks, @timheap!

**Pull request merged**
