### PR TITLE
Allow password resets to be disabled independently

### LINKED ISSUE #467: Allow password resets to be disabled independently
Right now, settings.WAGTAIL_PASSWORD_MANAGEMENT_ENABLED controls the availability of both the Wagtail password change page and the password reset flow. Someone might want to disable password resets while keeping the password change page, so I propose adding another setting (WAGTAIL_PASSWORD_RESET_ENABLED?) to provide more flexibility.

On a related note, setting WAGTAIL_PASSWORD_MANAGEMENT_ENABLED to False doesn't actually disable the relevant views, just removes the links to them.

### PR DESCRIPTION
**Pull request by ninepints**
Fixes #467 (sorry about opening duplicate issues, I'm bad at GitHub)

### CODE REVIEW

**Comment by davecranwell** [comment]
Hi @ninepints we'd like to merge this if you're able to make the changes @kaedroho mentions above. Would you have some time to make them?

**Comment by ninepints** [comment]
Hey, sorry, I wound up moving at the end of the summer and completely forgot about this. Just merged in a year of commits and added some documentation. I'll try to look at tests soon.

**Comment by ninepints** [comment]
I might be in over my head - it's easy enough to change the settings during testing (https://docs.djangoproject.com/en/1.8/topics/testing/tools/#overriding-settings) but at that point the views will already be registered, correct? The solutions I can think of are:

1) unregister the views for testing based on the setting_changed signal
2) always register the views and have them 404 based on the settings

but maybe someone who actually knows what they're doing should chime in :sweat_smile:

**Comment by ninepints** [comment]
Views updated and unit tests added. One of the CI builds failed, but looking at the logs it's not obviously my fault.

**Comment by gasman** [comment]
Looks good to me! I'd just propose one small tweak - if `WAGTAIL_PASSWORD_RESET_ENABLED` is not specified in settings, then it should default to the value of `WAGTAIL_PASSWORD_MANAGEMENT_ENABLED` (which in turn defaults to True). That way, existing projects with `WAGTAIL_PASSWORD_MANAGEMENT_ENABLED = False` will keep their current behaviour, and won't have password resets suddenly enabled.

**Comment by gasman** [comment]
Merged (with suggested tweak and some extra tests) in f0915e9fdaaf2d181db38dd1439e18f10d3b9cef. Thanks!

**Pull request closed without merging**
