### PR TITLE
added success message after image update

### PR DESCRIPTION
**Pull request by shredding**
My PM asked me many-a-time, if the image is now really stored, because it's simply gone after clicking the update button in the bulk-image-upload.

Can we add a ui feedback like this?

### CODE REVIEW

**Comment by davecranwell** [comment]
Hi @shredding thanks for addressing this. 

However there's an existing PR to remove the separate upload interface altogether, instead having users upload images directly into the image listing. That gives them the feedback they need as the images upload: https://github.com/torchbox/wagtail/pull/1234

I think I'd rather we take #1234's approach rather than trying to main a separate interface any more.

Please feel free to try out 1234 and perhaps even add your tweaks to that instead.

**Comment by shredding** [comment]
perfect.

**Comment by gasman** [comment]
It's not clear to me what the current status of #1234 is, and what the prospects of it are of it getting completed/merged any time soon. Until that's determined, I don't think we should put off making incremental improvements to the existing interface, so I'll reopen this.

**Comment by davecranwell** [comment]
Fair point re #1234. It's not something I'm going to have time to address in the near future and the changes @shredding has done here are so minor they might as well be merged in the meantime.

**Comment by davecranwell** [comment]
Note that #1234 is now complete.

**Comment by gasman** [comment]
Merged in 6422c7f61869084fae8f2e0de9e24d56ef9e1729 - thanks!

**Pull request closed without merging**
