### PR TITLE
Add help text to steer editors away from creating non-routable pages

### PR DESCRIPTION
**Pull request by gasman**
Adding help text to the explorer at the root level (and any other place where no site is configured), as proposed in https://github.com/torchbox/wagtail/issues/1583#issuecomment-131078851. @davecranwell might want to tweak the styling here (it gets an extra left margin for being the first cell of a table row, which we probably don't want).

Incorporates the display fix from #1611.

### CODE REVIEW

**Comment by tomdyson** [comment]
@davecranwell to review w/c August 24th.

**Comment by gasman** [comment]
@davecranwell Any chance this can be reviewed today please? I think it's really important to get this into 1.1.

**Comment by davecranwell** [comment]
I'd prefer that we don't use terminology like "record" and that we also provide links towards the system we're requiring them to use, in keeping with the "Why not create one?" link we use elsewhere. 

Consider instead: 
> "There is no site set up for this location. Pages created here will not be accessible at any URL until a site is associated with this location. [Configure a site now](link)". 

And the one on the Root page:
> "The root level is where you can add new sites to your Wagtail installation. Pages created here will not be accessible at any URL until they are associated with a site. To add pages to an existing site, create them as children of the homepage.  [Why not configure a site now?](link)

I dislike the placement of the `help-block` messages you're using, although they're currently your only real option (the banner messages would be missed), so that's not really your problem. 

The fact that the message bisects the "Index" page from its children beneath it is a perfect example of the issue [I've raised on previous occasions](https://groups.google.com/forum/#!topic/wagtail-developers/-ET8o6mmWZc) concerning the "full bleed" style and the placement of the column headers. Neither design motif allows us to insert components into the page which are global or ancilliary in nature, since the whole width is taken up displaying items in a list which are meant to all be of the same type and design.

However I suspect we won't be able to solve that before we want to launch this fix, so I'm OK with it for now.

**Comment by gasman** [comment]
@davecranwell

> The root level is where you can add new sites to your Wagtail installation. Pages created here will not be accessible at any URL until they are associated with a site. To add pages to an existing site, create them as children of the homepage. [Why not configure a site now?](link)

Putting the "Why not configure a site now?" link at the end is awkward. It makes it sound like that's the action associated with "To add pages to an existing site...", when actually that sentence is meant to politely steer the user away from fiddling with sites.

Switching those around might fix it, but it feels like we ought to try and make the "adding pages to an existing site" text more emphatic now, to counteract the call-to-action from the link. Maybe splitting it into two paragraphs...

> The root level is where you can add new sites to your Wagtail installation. Pages created here will not be accessible at any URL until they are associated with a site. [Configure a site now.](link)
>
> If you just want to add pages to an existing site, create them as children of the homepage instead.

Does that sound OK? Too informal?

**Comment by davecranwell** [comment]
That sounds fine to me, not too formal at all.

**Comment by gasman** [comment]
Rebased, wording updated as agreed, and additional tests/fixes added (we were erroneously showing the signposting messages on the search results / usage results views too)

**Pull request merged**
