### PR TITLE
Introduce generic admin class-based views/templates, and port wagtailsites to use them

### PR DESCRIPTION
**Pull request by gasman**
Was originally doing this as part of the collections feature, but that pull request is going to be big enough already without adding in a tangent like this - so I've used wagtailsites as the guinea pig to allow this to be reviewed and merged separately.

This doesn't go as far as the other 'modeladmin' implementations from myself, @kaedroho and @ababic - it's just the minimal implementation that will save me from mass copying-and-pasting for the collections feature. In particular, it doesn't combine the views into a single 'master' class, or register URLs / permissions / menu items - I suggest we look at those features later, and cherry-pick the best ideas/approaches from the existing implementations.

Depends on (and incorporates) #1606.

### CODE REVIEW

**Comment by ababic** [comment]
@gasman I think the class-based views are an excellent addition. It can only be a good thing to have something like this in place to build upon. I've been thinking just this weekend about refactoring my particular approach to make a much clearer distinction between 'view functionality' and the configuration element... Ideally, I'd like to abandon the dependancy on Django's ChangeList view, and replace with a purposefully-built set of class-based views that would do as much of the heavy lifting as possible (with the modeladmin classes simply providing a way to hook in to them). Your generic views here serve as a great starting point for this.

**Comment by gasman** [comment]
Have now incorporated @kaedroho's feedback, and rebased on master:

* `template` is now `template_name`
* `PermissionCheckedView` is now `PermissionCheckedMixin`, a pure mixin class
* `CreateView` now implements `get_add_url`, for consistency with the edit/delete views
* `IndexView`, `EditView` and `DeleteView` now provide `object` / `object_list` in the template context (alongside the variable specified in `context_object_name`, which is now optional)

Ready for re-review!

**Comment by tomdyson** [comment]
Good one, @gasman. Release notes?

**Comment by gasman** [comment]
@tomdyson Hmm, good question. If we're counting this as an internal rewrite then it doesn't really need release notes. (I don't think we want to push this as something for third-party apps to use just yet - leaving it internal-only for a release or two will give the API a chance to stabilise, and hopefully let us add the URL/permission/menu bells and whistles.)

**Comment by SalahAdDin** [comment]
Very good man :D

**Pull request merged**
