### PR TITLE
Added manage.py for demosite to make contributing easier

### PR DESCRIPTION
**Pull request by kaedroho**
In https://github.com/torchbox/wagtail/pull/1121 we merged the models/data from Wagtaildemo into Wagtail. The original intention of this was to provide a base for writing unit tests against.

I found that if we add a ``manage.py`` file (and some settings files) into Wagtail, we could actually launch this app.

I think this would make contributing to Wagtail much easier as you no longer need to setup wagtaildemo (or mess around with Python paths in order to test UI changes).

**Usage:**

Once you have Wagtail cloned locally and tests are running (see: http://docs.wagtail.io/en/latest/howto/contributing.html#running-the-unit-tests), run the following commands.

```
demosite.py migrate
demosite.py createsuperuser
demosite.py loaddata demosite.json
demosite.py runserver
```

The first three commands only need to be run on initial set up.

This doesn't require Vagrant or PostgreSQL to be installed (it uses SQLite)

### CODE REVIEW

**Comment by gasman** [comment]
It's a neat trick, and very satisfying to see that it works at all, but I can't see it being particularly usable as a development aid in practice, especially as we're trying to reduce the number of suggested entry points into Wagtail development.

Compared against developing against a real project, it has inherent limitations (lack of templates, inability to change models without breaking unit tests, unlikely to be kept up to date with updates from the 'real' wagtaildemo repo); for certain kinds of work, such as UI tweaks, it would indeed be sufficient, but documenting the specific set of circumstances where it's usable, and at what point you should graduate to a 'proper' project setup, is surely going to be more hassle than simply telling people to use a real project from the start.

**Comment by kaedroho** [comment]
Thanks for the reply @gasman!

I like this way as it requires very little setup to get it running. If the tests run, this will run too. I think that's nicer than having to ask everyone to install Vagrant (then play around a bit with the virtualenv/pythonpath).

> but I can't see it being particularly usable as a development aid in practice

I've used it to do a few reviews in the past week and it's been very useful.

For certian things that require models changes, I can't think of a reason why you can't add an extra app to "wagtail/tests" and add it to demosite settings (I would actually encourage that).

> especially as we're trying to reduce the number of suggested entry points into Wagtail development.

I think removing the need for developers to have to setup wagtaildemo and Vagrant is a step in the right direction for developer experience.

**Comment by gasman** [comment]
The problem I'm seeing here is that essentially, this change makes it really easy for developers to set up a 50% (or maybe 80%, 90%...) functional Wagtail installation with a slightly weird project structure. That doesn't seem like a desirable thing for either the developer, or us providing developer support.

It works fine for you, because you built it and know which particular 90% is meant to be functional in this setup, but the typical new developer won't know that. Even if you could communicate that in the documentation, we're still going to have to maintain two sets of instructions - one for this simple setup, and another for a full project setup so that people can work on the remaining 10%.

> For certian things that require models changes, I can't think of a reason why you can't add an extra app to "wagtail/tests" and add it to demosite settings (I would actually encourage that).

You can do that, but it's certainly not as convenient as hacking an existing model. If we're trading that convenience off against the convenience of not having to make a four-line pythonpath tweak - I'd choose the hackable models any day :-)

Also, I can't see this making a huge amount of difference regarding the need for Vagrant. You still need libsass / Pillow either way, and the other potentially troublesome dependencies of wagtaildemo (Postgres, Elasticsearch, OpenCV) can be disabled by a suitably clued-up developer, just as they're disabled here. If you want to lower the barrier for those non-Vagrant developers, then I think the right thing to do would be to offer a simplified version of wagtaildemo as a conventional project - either as a repo of its own, or (perhaps more realistically) an alternative settings file within the existing wagtaildemo repo.

**Comment by kaedroho** [comment]
Alright, will close.

**Pull request closed without merging**
