### PR TITLE
[Fix #2313] replace pushd with cd

### LINKED ISSUE #2313: Error running "npm install"
Running `npm install` (bash on ubuntu 14.04) resulted in the following error:

> wagtail@1.0.0 install /path/to/wagtail
> pushd ./client; npm install; popd
> sh: 1: pushd: not found

Due to this issue I wasn't able to build the static assets for the wagtail admin UI. It took me a while to figure out what was causing the problem. As stated in http://stackoverflow.com/questions/5193048/bin-sh-pushd-not-found/5193092#5193092 `pushd` is a builtin function in bash, but node uses `sh` by default.

I finally changed
`"install": "pushd ./client; npm install; popd",`
to
`"install": "bash -c 'pushd ./client; npm install; popd'",`
in `package.json`.

I have no idea how to fix this issue for all operating systems, as I think my workaround will only work on linux.

### PR DESCRIPTION
**Pull request by JoshBarr**
Fixes #2313 by removing bash specific `pushd` and `popd`

### CODE REVIEW

**Comment by justinvdm** [comment]
:+1: from me fwiw

**Comment by gasman** [comment]
Seems to work here! I now have a `client/node_modules` directory that I didn't have before, so I guess this was silently failing for me too... (I guess we ought to have that in `.gitignore`, right?)

**Comment by JoshBarr** [comment]
Provided Travis is happy, this fix should be good to merge. Do the same guidelines apply to merging hotfixes as new features.... i.e, does someone else have to merge this for me?

**Comment by gasman** [comment]
@JoshBarr Cheers! I'll merge this now.

**Comment by gasman** [comment]
Merged in cf23387843a9d3a6897a0de928d3136a94f91711 + 2c25ce153eddbed0845f35f0820d85e3ccfae7c4

**Pull request closed without merging**
