### PR TITLE
Remember tree location in page chooser when switching between Internal / External / Email link

### LINKED ISSUE #2640: Editing an 'Internal link' via the RichText editor doesn't remember the target page as expected
When running `1.5rc1`, the 'Internal link' tab of the link editor interface seems to forget about the target page after clicking 'External link' or 'Email link', then 'Internal link' again.

### PR DESCRIPTION
**Pull request by gasman**
Fixes #2640

### CODE REVIEW

**Comment by gasman** [comment]
Hi @ababic - could you give this a quick review please?

**Comment by m1kola** [comment]
It looks like new a feature because Wagtail 1.4.* behaves the same way as 1.5. Are you sure that we need to merge this into 1.5.1?

**Comment by gasman** [comment]
@m1kola Yep, true - I think this could easily wait for 1.6 instead.

**Comment by ababic** [comment]
@m1kola @gasman I could be wrong, but hasn't the ability to 'edit' a link
only been in since 1.5? Forgetting selections between tabs when adding a
link isn't such a big deal (the editor likely know what they want to link
to, and can redefine things without too much trouble), and if that were the
issue being solved, I would gladly agree on postponing to a later release.

But, forgetting about pre-defined data when editing a link is, I think, a
potentially frustrating bug, and one worth fixing sooner, if it's not too
much trouble.

@gasman, what's the best way to review other's pull requests locally? It's
not something I've done before.

**Comment by m1kola** [comment]
> I could be wrong, but hasn't the ability to 'edit' a link only been in since 1.5?

That's right. I checked behaviour of tabs in chooser while adding a link on Wagtail 1.4.

> @gasman, what's the best way to review other's pull requests locally? It's
not something I've done before.

I use [`wagtaildemo`](https://github.com/torchbox/wagtaildemo) project and editable installation of Wagtail (using `pip install -e`). Also I think the [`git pr`](http://docs.wagtail.io/en/v1.5/contributing/committing.html#check-out-the-code-locally) alias is very useful ;)

**Comment by ababic** [comment]
Thanks for the tips @m1kola!

**Comment by m1kola** [comment]
Merged in ba807e5f45812e85bf83b49bf04d2c796ef63cda + parents.

Thanks @gasman and @ababic!

**Pull request closed without merging**
