### PR TITLE
Account settings button

### PR DESCRIPTION
**Pull request by jjanssen**
These are some adjustments in favour of #1323 and its proposal to make it more clear for the end-user.
Its output is tested in IE9, IE10, IE11, Edge, Chrome, Firefox ESR (v45), iOS9.

A few functionalities to recall:
- Account settings only shows the first name and never the full name (Tom is short, Janneke is medium, Hendrik-Jan is large).
- If a name is longer than intended, it will be adding …
- If a translation of ‘Account Settings’ or ‘Login’ is longer than intended it will be adding…

This is mainly we have a fixed height footer in the navigation in order to maintain a predictable scrolling area for the upper items of this list is longer than the screen.

**What it looks like**
If no gravatar is set:
a-no-gravatar

If a gravatar is set:
a-gravatar￼

On mobile:
a-mobile

**Open issue**
The adding of the Wagtail version number in the settings menu enables the following bug (#2802)
This applies to the current master branch, but also to this feature.

### CODE REVIEW

**Comment by tomdyson** [comment]
Thanks, @jjanssen, looks good! Are we dropping the circular mask on the gravatar?

**Comment by jjanssen** [comment]
Thanks @tomdyson! I wouldn't say ditching the circular mask on the gravatar. For the sidemenu the square size makes more sense to be eye-catching. Making it round while attached to the side looks a bit silly. For displaying within the content-area I would still go with the circular mask.
But I am happy to change it if we decide it's a breach of style :-)

**Comment by tomdyson** [comment]
Hi @jjanssen, could you please add a larger screenshot showing the menu in context? Ideally with mask / no-mask options :)

**Comment by jjanssen** [comment]
Rough sketch ;-)

**Without the mask**
wagtail-admin-square

**With mask**
wagtail-admin-mask

**Comment by tomdyson** [comment]
@jjanssen thanks! I _think_ I still prefer the masked version, but will defer to experts. @tmsndrs / @JoshBarr / @jonnyscholes / @ollywillans?

**Comment by tmsndrs** [comment]
I think the first (square) option is probably going to be easier for people to use. Circles work well when people have a photo with the right composition but the square will be more forgiving. 

Can I be really picky and suggest a little more margin above 'account settings' when the menu is open? It feels a bit tight.

**Comment by jjanssen** [comment]
Sure @tmsndrs 

I'll wait for some feedback from the others, so I can pick it in one batch.

**Comment by SalahAdDin** [comment]
I like it, i like it!

**Comment by SalahAdDin** [comment]
Applied it?

**Comment by jjanssen** [comment]
Nope, was cleaning up branches a little too enthousiastic

**Comment by gasman** [comment]
Hi @jjanssen - just a couple of issues I've spotted:

- if the user has no email (e.g. they were created using `./manage.py createsuperuser` and no email was provided at that point) and the avatar element is missing, the alignment is broken:
screen shot 2016-09-30 at 16 29 24
- on the settings -> users -> edit page, clicking anywhere in the 'Account' tab of the form causes the popup to toggle up and down due to the re-use of the 'account' ID.

Other than those, looks good!

**Comment by jjanssen** [comment]
Hi @gasman, thanks for the feedback! I have processed the issues and updated the PR.
Also made a little change in the base colouring of the element, based on the PR for #2985.

**Comment by gasman** [comment]
Looks good to me! Merged in 2992d90e97a9eb776d45c09b4bd50499ced555eb.

**Pull request closed without merging**
