### PR TITLE
Remove dependency on django compressor

### PR DESCRIPTION
**Pull request by kaedroho**
Refs #2124 

This pull request removes the dependency on django-compressor. We've previously used it for bundling CSS and JavaScript but the 2.0 release adds some dependencies with compiled extensions which make it (and Wagtail) more difficult to install.

This should also remove the need to run ``django-admin compress`` on every deploy unless the project itself uses Django compressor.

### CODE REVIEW

**Comment by tomdyson** [comment]
Hi @timheap, are you able to look at this one?

**Comment by balazs-endresz** [comment]
The problem with this approach is that the static file urls will be the same after their content is changed, which means you couldn't use a far future Expires header. Using ManifestStaticFilesStorage or CachedStaticFilesStorage should be able to help with this:
https://docs.djangoproject.com/en/1.9/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage
But that would apply to the whole site not just to wagtailadmin.

**Comment by timheap** [comment]
I found some more references to django-compressor, in the docs, docstrings, and comments that need removing:

```
docs/reference/hooks.rst:231:  Add additional Javascript files or code snippets to the page editor. Output must be compatible with ``compress``, as local static includes or string.
docs/reference/hooks.rst:260:  Add additional CSS or SCSS files or snippets to the page editor. Output must be compatible with ``compress``, as local static includes or string.
docs/advanced_topics/performance.rst:28:Without a persistent cache, Wagtail will recreate all compressible assets at each server start, e.g. when any files change under ``./manage.py runserver``.
wagtail/wagtaildocs/static/wagtaildocs/css/add-multiple.css:3:STATIC_URL setting. However, django-compressor consistently places the compiled
wagtail/wagtailadmin/static_src/wagtailadmin/scss/_variables.scss:4:// STATIC_URL setting. However, django-compressor consistently places the compiled
wagtail/tests/settings.py:138:COMPRESS_ENABLED = False  # disable compression so that we can run tests on the content of the compress tag
```

I have not had a chance to test this with the ManifestCacheMiddleware yet. If it works with that, and the above references are removed, then I am happy for this to be merged.

**Comment by JoshBarr** [comment]
A quick question... How do we intend to transform/minify JS for the admin in lieu of `{% compress %}`? Is the plan to bundle/minify everything offline via `gulp` or similar and manually include references to the built assets in the templates? 

Today I was looking at an interesting project, [django-webpack-loader](https://github.com/owais/django-webpack-loader) for integrating Webpack bundles with Django. I've got it set up with Wagtail, but didn't manage to push it while GitHub was down... We would need some of this infrastructure in place to transform React components for the admin and split up the JS into re-usable modules.

**Comment by davecranwell** [comment]
From the discussions we've had recently, I don't believe we plan to minify _any_ JS or CSS for the admin. The thinking was that minification is an optimisation best left to the implementor, so they can choose their solution rather than have one enforced. In Torchbox's case for example, we'll almost certainly continue to use django-compressor in most of our production projects - _we've_ never had any trouble with it.

Separately however, @kaedroho has been looking into rebundling of some of our JS to avoid some needless repetition. Webpack or browserify were considered but I'm not sure the outcome there.

**Comment by gasman** [comment]
As @davecranwell says, the plan *for now* is to leave the admin JS and CSS un-minified. However, it's not really a case of 'leave it up to the implementor' - in the absence of the `{% compress %}` tags it won't be possible for implementors to take advantage of django-compressor for the admin even if they do want to (i.e. even if they have it enabled for their front-end).

For that reason we probably do want to continue looking at adding minification / bundling to our gulp toolchain - but that's not as urgent as dropping django-compressor from our requirements.

**Comment by balazs-endresz** [comment]
About the versioning: django-cms solves that by appending only the CMS version to the url:

https://github.com/divio/django-cms/blob/develop/cms/templates/cms/wizards/base.html#L16
https://github.com/divio/django-cms/blob/a027f080b0c5a65f12f3879e389063f37c32a4d0/cms/templatetags/cms_static.py#L30
https://github.com/divio/django-cms/blob/a027f080b0c5a65f12f3879e389063f37c32a4d0/cms/utils/urlutils.py#L63

That looks even less intrusive than adding `ManifestStaticFilesStorage` to the project template. And it wouldn't require adding that in for (some) existing wagtail sites.

**Comment by davecranwell** [comment]
https://css-tricks.com/strategies-for-cache-busting-css/ which is quite possibly out of date, suggests that query string cache busters aren't understood by some proxies. We may or may not want to consider that.

**Comment by balazs-endresz** [comment]
That might be still a valid point about the proxies. And actually, this was added in to django-cms only a month ago: https://github.com/divio/django-cms/pull/4874#issuecomment-167826521

**Comment by SalahAdDin** [comment]
Why will you deprecated this requirement?

**Comment by kaedroho** [comment]
@SalahAdDin please read the description at the top

**Comment by gasman** [comment]
@kaedroho to update all `{% load static %}` tags to ensure that we're compatible with ManifestStaticFilesStorage.

**Comment by kaedroho** [comment]
Rebased

**Comment by timheap** [comment]
This looks good. Combined with #2192, this is compatible with ManifestStaticFilesStorage, which was my only outstanding concern.

**Comment by gasman** [comment]
Merged in daba4aff841fa312bb47615dc85e33a3ddad06bc + parents, along with a documentation update 20b42ad7d9644de730441a60c2f8249e6c4a162f.

**Comment by timheap** [comment]
Sorry, I had another look for references to django-compressor, and I found some more that were missed:

```
# Results trimmed slightly to remove false positives
$ ack-grep -i 'compress' --ignore-dir venv --ignore-dir .tox --ignore-dir node_modules
wagtail.egg-info/requires.txt:2:django-compressor>=1.4
docs/reference/hooks.rst:231:  Add additional Javascript files or code snippets to the page editor. Output must be compatible with ``compress``, as local static includes or string.
docs/reference/hooks.rst:260:  Add additional CSS or SCSS files or snippets to the page editor. Output must be compatible with ``compress``, as local static includes or string.
docs/advanced_topics/performance.rst:28:Without a persistent cache, Wagtail will recreate all compressible assets at each server start, e.g. when any files change under ``./manage.py runserver``.
wagtail/wagtailadmin/static_src/wagtailadmin/scss/_variables.scss:4:// STATIC_URL setting. However, django-compressor consistently places the compiled
wagtail/tests/settings.py:138:COMPRESS_ENABLED = False  # disable compression so that we can run tests on the content of the compress tag
etc/nginx.conf.sample:19:    # Enable content compression for text types.
CHANGELOG.txt:8: * Wagtail no longer depends on django-compressor
```

**Pull request merged**
