### PR TITLE
Please, move the styleguide away from the main menu

### PR DESCRIPTION
**Pull request by MechanisM**

### CODE REVIEW

**Comment by zerolab** [comment]
Hi @MechanisM,

Thank you for you pull request. The Wagtail styleguide is a contrib app for Wagtail development only. See http://docs.wagtail.io/en/latest/howto/contributing.html#styleguide

Will let @davecranwell chip in, but I think it makes a lot of sense to keep it as visible as possible.

Cheers,
Dan

**Comment by davecranwell** [comment]
I'm not that fussed about where this lives, provided that it's accessible through the menu somewhere.
As @zerolab points out - you're not expected to have the styleguide enabled unless you're developing wagtail itself. You may not like it where it currently sits though.

Having said that, you're the only person to suggest moving it and I'd rather wait to hear other people's views before merging this.

**Comment by MechanisM** [comment]
Well, actually it doesn't look like for adding some content. Other main menu items is for editing and browsing content, while Styleguide is for other purposes and look wierd around things like Pages, Documents, Images etc..

**Comment by gasman** [comment]
The styleguide is not really a 'setting', though, and we don't want Settings to become a dumping ground for "we weren't sure where to put this"...

However, in this case I'm mildly in favour of moving it. I think it's a good general rule for developers and 'power users' to have a view of the app that's as close as possible to the view that ordinary users get, so that we don't lose sight of how it looks and feels in the real world... kind of like the reason we use Lorem Ipsum as filler text instead of 'aaaaaaaaaaaaaaaa'... and making the main menu less cluttered is a step towards that.

**Comment by kaedroho** [comment]
Is there anywhere else we could put it? The dashboard?

**Comment by davecranwell** [comment]
The dashboard is a kinda menu I suppose, although its content is tailored much more to the user. I suppose you could argue adding the styleguide is a trailoring, of sorts, towards developers? Eeh. 

As much as I don't want settings to be a dumping ground, I'd also rather not set the precedent that the primary menu is off-limits to anything except "content", otherwise we get into semantic debates like this one :P

Given the options, I think I favour Settings.

**Comment by MechanisM** [comment]
Where to put menu items for things like that?
Screenshot
I've added it into Settings. Same for Styleguide

**Comment by zerolab** [comment]
imho, this calls for a "Developer" or ("Development") menu section, next to Settings.

**Comment by davecranwell** [comment]
I'd tentatively support that. I guess it wouldn't be visible if it had no children enabled.

**Comment by MechanisM** [comment]
These items meant to be for developers. Developers knows where to find it :smile:, while for regular users it should be hidden.

**Comment by kaedroho** [comment]
Another thing that might be useful to have in a developers menu a "Report issue" button that takes them to https://github.com/torchbox/wagtail/issues/new

**Comment by SalahAdDin** [comment]
Wow @MechanisM, can you teach me how do somethin like your web dashboard?

**Comment by gasman** [comment]
Merging, since there's general (albeit weak) support for moving it into settings. Anyone who feels strongly about better solutions (such as a Developer submenu) can open a new issue/PR for that :-)

**Comment by SalahAdDin** [comment]
@MechanisM please :D

**Pull request merged**
