### PR TITLE
Added support for indexing relations in Elasticsearch

### PR DESCRIPTION
**Pull request by kaedroho**
This pull request implements the new syntax as descibed in #459 which allows related objects to be indexed in Elasticsearch.

This is useful for indexing tags, "child objects", foreign keys, etc. A relation can be indexed from both sides.

It uses Elasticsearch's "nested type": https://www.elastic.co/guide/en/elasticsearch/reference/1.6/mapping-nested-type.html

This doesn't implement the ability to filter search results across relationships. ``FilterField``s can be indexed but you'll need to come up with a custom query to use them for the moment. This will be implemented in a later pull request.

### CODE REVIEW

**Comment by kaedroho** [comment]
This PR could be used to come up with a more generic solution for #613. Possibly by listening on Django's ``m2m_changed`` signal whenever a many to many field is put in a ``index.RelatedFields``

**Comment by kaedroho** [comment]
Ready for review!

**Comment by tomdyson** [comment]
Hi @timheap, do you have time to review this in the next few days (ahead of RC for 1.3)?

**Comment by timheap** [comment]
I should be able to take a look on Friday, yep.

**Comment by timheap** [comment]
Does this support nested `RelatedFields`? It does not seem to support it yet, but I do not think the modifications would be too hard. That would allow you to do something like:

```
class RelatedPage(models.Model):
    page = ParentalKey('ListPage', related_name='related_pages', ...)
    related_page = models.ForeignKey(Page, ...)

class ListPage(Page):
    body = RichTextField()

    search_fields = [
        SearchField('title'),
        SearchField('body'),
        RelatedFields('related_pages', [
            RelatedFields('related_page', ['title']),
        ]),
    ]
```

Something like this would still be possible by adding a `related_title()` method to `RelatedPage`, and indexing that instead, but people will attempt this first, assuming that `RelatedFields` can be nestable.

Otherwise, everything looks good.

**Comment by gasman** [comment]
I'm wondering whether we need to document the fact that this only works on Elasticsearch... but on reflection, I think that's a more general documentation issue that's out of scope for this ticket. (On a technicality, defining whether RelatedFields is or isn't supported on the database backend gets kind of philosophical, because indexing is a no-op - you can define them, and the backend will merrily ignore them, but you can't actually call that behaviour incorrect because there's no formal standard of "correctness" for search results.) Will raise that at the next Wagtail meeting instead...

**Comment by gasman** [comment]
Merged in 2c765a7462a8270cb471f74d632fc1c2a1aeb58a + parents.

**Pull request closed without merging**
