### PR TITLE
Show a message to users who do not have permission to access admin 

### LINKED ISSUE #1486: Login attempts result in different behaviour for users known by django but with insufficient permissions
1. create a new user in wagtail,
2. assigned it to a group which has no admin access
3. try to log into wagtail admin as that user

The result is a redirect back to the login without any feedback whatsoever.

I'd expect the user to receive the same error response as someone logging in with completely unknown credentials. A difference in results indicates to anyone probing the site maliciously, that a set of tested credentials matches a real user.

### PR DESCRIPTION
**Pull request by timheap**
Fixes #1486.

As part of doing this, I found a bug in the admin access tests where a user was not logged correctly, but this was not caught by the tests. I have fixed the tests to assert that users are actually logged in.

### CODE REVIEW

**Comment by davecranwell** [comment]
Is this update still giving users different messages depending on status? That still seems like a leak to me.

**Comment by tomdyson** [comment]
Nice one @timheap!

**Comment by gasman** [comment]
@davecranwell With this change, we go from no message at all when logging in as a valid-but-no-wagtailadmin-permission user, to getting a "You do not have permission to access the admin" message. Given that you have to provide a valid username/password to see the difference, I don't think there's a risk of information leakage - that's more of a concern for password reset forms (if you're thinking of the same issue I'm thinking of).

**Comment by davecranwell** [comment]
Ah yes, of course. If the password would have to be correctly entered, then leaking whether they're an admin or not is the least of our worries :)

**Comment by gasman** [comment]
Merged in #a2bc7341f27ec774c50381cc409b6f6376daf3a8 + parents - thanks!

**Pull request closed without merging**
