### PR TITLE
Quick fix for #1265

### PR DESCRIPTION
**Pull request by chhantyal**
I am not sure if this is right way, and if error doesn't have any other consequences.

But my quick test says it works.

Fix for #1265

### CODE REVIEW

**Comment by chhantyal** [comment]
Ok, there is some problem with your Drone setup.

**Comment by kaedroho** [comment]
This is based on an older version of wagtail. Could you rebase it onto the latest master?

**Comment by chhantyal** [comment]
I just uninstalled and reinstalled - but getting same error

**Comment by kaedroho** [comment]
The drone thing could be ignored. The reason it's complaining is your master branch is really old and predates when we added the drone config and enabled flake8 on wagtail.

If you'd like to fix it though. Use git rebase to move that commit on top of the latest master: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by kaedroho** [comment]
Merged in a0dc8b39a67ec198f5ddfde07d4d12809c2c13c6 (master) and f5f068b10d0e4cc6fd34aa4449cb75fb750117e2 (0.8.x)

Thanks!

**Pull request closed without merging**
