### PR TITLE
New features for wagtailforms

### PR DESCRIPTION
**Pull request by m1kola**
One of our clients asked us to implement a module for managing polls and surveys with Wagtail admin. I have implemented [`wagtailsurveys`](https://github.com/torchbox/wagtailsurveys) module based on `wagtailforms`. I tried to make implementation as much compatible with `wagtailforms` as possible. This PR should suppress `wagtailsurveys` and give implementors ability to create polls, surveys (and other functionality) with `wagtailforms`.

List of features:
* Allow implementors define custom form submission model on per `Page` basis.
* Allow implementors extend list of fields for submissions listing view / CSV export.
* Allow implementors perform custom validations using user / page object.

--

Review order:

- [ ] This PR
- [ ] A new structure for `wagtail.wagtailforms.tests` - https://github.com/m1kola/wagtail/pull/1
- [ ] New tests - https://github.com/m1kola/wagtail/pull/2

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Can you work in this https://github.com/torchbox/wagtail/issues/1348 adittionally?

**Comment by m1kola** [comment]
Yesterday I started work on tests for this PR:

- [ ] A new structure for `wagtail.wagtailforms.tests` - https://github.com/m1kola/wagtail/pull/1
- [ ] New tests - https://github.com/m1kola/wagtail/pull/2

> Can you work in this #1348 adittionally?

It seems to me that will be better to implement this issue in a separate PR. BTW, you can start work on it ;)

**Comment by SalahAdDin** [comment]
Thanks man!

**Comment by m1kola** [comment]
The implementation and test are ready to code review (review order listed in the [first post](https://github.com/torchbox/wagtail/pull/2617#issue-154755959))

I'll move documentation in a separate PR (I've created #2945 for this).

**Comment by m1kola** [comment]
All PRs had been rebased on top of the `master` branch.

**Comment by gasman** [comment]
Merged in 5fdbae4be78e4d9928b4bed3b1207f1a991227b0 + parent. Haven't added a release note at this point - as I see it, this is more of an internal refactor until we have documentation for end-users to customise FormSubmission etc.

**Pull request closed without merging**
