### PR TITLE
Add editor name to moderation notification

### PR DESCRIPTION
**Pull request by vden**
A minor moderation notification change proposed in #1322.

How do we push new translation strings to Transifex? Should I include it into PR somehow?

### CODE REVIEW

**Comment by prydie** [comment]
Looks good to me

**Comment by SalahAdDin** [comment]
:+1:

**Comment by kaedroho** [comment]
Merged in 0a9f2cfadda04f376d2c1d92a07ac26a7e72e84b Thanks!

In testing, I noticed the new "Hello {name}," bit doesn't fallback to the users username if their full name isn't set. I'll create a new issue for that.

**Comment by SalahAdDin** [comment]
Great idea!

**Pull request closed without merging**
