### PR TITLE
Added new image operations

### PR DESCRIPTION
**Pull request by kaedroho**
This PR rewrites all of Wagtails image operations (``fill``, ``max``, etc) in a new format and adds code to Filter to load/parse/run the new operations.

This doesn't remove any old code and the new code doesn't get used yet (you must access it through the shell). I did this to keep this PR small and easy to review, but it should not be merged without merging later PRs as well.

The new format is intended to be more readable, testable and extensible than what we've already got. It's also making use of Willow.

### CODE REVIEW

**Comment by kaedroho** [comment]
Just made some improvements to the way operation errors are handled in f9e682e:
 - Invalid operations should now raise InvalidFilterSpecError from their __init__ method if the passed arguments are invalid.
- Created "construct" method which is called by __init__. If this method raises a ValueError, that error would be reraised as an InvalidFilterSpecError.
- Argument count is validated before calling construct so we no longer need to catch all TypeErrors.

**Comment by davecranwell** [comment]
Might this be something you can add to this PR?: https://github.com/torchbox/wagtail/issues/595

**Comment by kaedroho** [comment]
These PRs are primarily focused on refactoring so I'd prefer we did that in a separate PR (I don't think it's a good idea to mix refactoring with new features).

**Comment by davecranwell** [comment]
Fair enough.

**Comment by timheap** [comment]
Looks good to me!

**Pull request merged**
