### PR TITLE
Rebuild translation files - fixes #1452

### LINKED ISSUE #1452: Translations in rc1 do not (fully) work
When I'm bootstrapping a new project from the project template via `wagtail start website` and change LANGUAGE_CODE to "de-de", the translation is very half-baked, although the translations seem to be available in the .po files.

Here is what I did.

1. `pip install -U wagtail==1.0rc1`
2. `wagtail start website`
3. `cd website`
4. `pip install -r requirements.txt`
5. `sed -i '' 's/en-us/de-de/' website/settings/base.py` to switch the locale to German.
6. `./manage.py migrate && ./manage.py createsuperuser`
7. `./manage.py runserver 0.0.0.0:8000`

When I open the wagtail admin in a browser, the login screen is still english but with some German words. It become even stranger after logging in: Most of the admin page is in English but the Settings menu and the Search box are in German. Documents and Images seem to be completely in English, the Page explorer.

image

image

Am I missing anything? The only pattern I could recognize are the missing .mo files in some modules. Could that be the reason?

### PR DESCRIPTION
**Pull request by gasman**
It appears that a whole load of .mo files were erroneously deleted in 64a630b8d5f3f009f1641d42f3a622f0159dfb38 - this PR re-fetches translations from Transifex and rebuilds them. Along the way I've added the missing plurals from the Russian translations (via Google Translate, but better than nothing...) that were causing compilemessages to fail - have also updated these in Transifex so that they hopefully won't disappear on the next pull.

### CODE REVIEW

**Comment by gasman** [comment]
@kaedroho No - I followed the instructions on https://github.com/torchbox/wagtail/wiki/Managing-Wagtail-translations. If there's anything missing from those steps, please could you update them accordingly?

**Comment by gasman** [comment]
@zerolab Thanks! Translation updated here and in Transifex now.

**Comment by kaedroho** [comment]
Done

**Comment by gasman** [comment]
Superseded by #1454

**Pull request closed without merging**
