### PR TITLE
Optimise JPEG images when generating renditions

### PR DESCRIPTION
**Pull request by kaedroho**
We've recently added support in Willow to make use of Pillow's image optimisation (not yet in a released version). This commit enables this in Wagtail.

All JPEGs are now optimised and saved in progressive format.

Before:
```
  7194 David_Mitchell_by_Kubik.width-200.jpg
 46720 grey_wagtail_by_lip_kee.width-1000.jpg
  6435 grey_wagtail_by_lip_kee.width-200.jpg
  8600 James_Joyce_in_1915.width-200.jpg
  7030 pied_wagtail_by_Marie_Hale.width-200.jpg
 81835 wagtail_at_Borovoye_Kazakhstan_by_Ken_and_Nye.width-1000.jpg
  8607 wagtail_by_fs-phil.width-200.jpg
  7238 wagtail_collects_insects_by_Maggi_94.width-200.jpg
 44082 wagtail_sproing_by_Jim_Bendon.width-1000.jpg
```

After:
```
  6989 David_Mitchell_by_Kubik.width-200.jpg
 43760 grey_wagtail_by_lip_kee.width-1000.jpg
  6122 grey_wagtail_by_lip_kee.width-200.jpg
  8125 James_Joyce_in_1915.width-200.jpg
  6680 pied_wagtail_by_Marie_Hale.width-200.jpg
 75575 wagtail_at_Borovoye_Kazakhstan_by_Ken_and_Nye.width-1000.jpg
  8121 wagtail_by_fs-phil.width-200.jpg
  6901 wagtail_collects_insects_by_Maggi_94.width-200.jpg
 41375 wagtail_sproing_by_Jim_Bendon.width-1000.jpg
```

Approximately 7% improvement.

### CODE REVIEW

**Comment by ddiazpinto** [comment]
As a note, the best performance is using quality=False when optimize=True. So, maybe It should be the default value.

**Comment by kaedroho** [comment]
Thanks again @ddiazpinto! I'll give that a try

**Comment by kaedroho** [comment]
That seems to have worked! ``wagtail_at_Borovoye_Kazakhstan_by_Ken_and_Nye.width-1000.jpg`` now goes down to 65344 bytes (21% improvement)

**Comment by ddiazpinto** [comment]
I think so, absolutely ;)

**Comment by gasman** [comment]
Looks good to me as it stands.

Regarding `quality=False` - surely that's just selecting the PIL default of 75 (http://pillow.readthedocs.io/en/3.3.x/handbook/image-file-formats.html#jpeg), which makes it not particularly surprising that it gives 20% smaller file sizes? :-) We decided early on that 75 was too low quality, hence setting our own default at 85.

**Comment by kaedroho** [comment]
Willow 0.4 released, I've added a commit to this PR updating it as a dependency of Wagtail

**Comment by gasman** [comment]
Merged in 882facf352af281d0b8eb1dd55b724cf35680e14 - thanks!

**Pull request closed without merging**
