### PR TITLE
Let block subclasses override their BoundBlock classes

### PR DESCRIPTION
**Pull request by akx**
This makes it easier to implement blocks that have some added logic
such as properties that need to be accessible from templates.

### CODE REVIEW

**Comment by gasman** [comment]
Hi @akx,

I'm not sure that this is a good idea - there's too much "magic" in the behaviour of BoundBlock already, where objects [act differently depending on how you access them](http://docs.wagtail.io/en/v1.3.1/topics/streamfield.html#boundblocks-and-values), and I'm concerned that allowing customisation here will make the behaviour even more unpredictable. (As a specific example of that: `StreamValue.__getitem__` [bypasses the `bind` method](https://github.com/torchbox/wagtail/blob/654347d65f4da5baa93ed412fc86f624e531b68a/wagtail/wagtailcore/blocks/stream_block.py#L298), so children of a StreamBlock won't receive the custom BoundBlock class.)

The way I see it, the BoundBlock mechanism exists primarily for the benefit of the containing block: it's essentially a way of saying "here's a block value, along with some extra information about the type of block, and how it should be rendered". With this change, control is being handed over to the child block, and the API doesn't seem as clean.

Can you give an example of how this would be used? That might help me understand the motivation for this change a bit better...

**Comment by akx** [comment]
Hey @gasman, thanks for checking this out.

So, my UC is that I have a page -- the home page for the site -- with a customizable list of quick links in the sidebar. One can choose whether to have a page link, or an external link. (And some other details which don't concern the discussion here. :) ) The list is implemented as a StreamField with only one block type, the `QuickLinkBlock`.

In templates I need to get the effective URL, i.e. either the external URL, if set, or the page's URL (otherwise). The `get_url()` fn below is the ugly workaround I implemented for that purpose.

```python
class QuickLinkBlock(StructBlock):
    page = PageChooserBlock(label=_("page"), required=False)
    external_url = URLBlock(label=_("external URL"), required=False)
    text = CharBlock(label=_("link text"), required=True)

    def get_url(self, value):    
        if value.get("external_url"):
            return value["external_url"]
        else:
            return value["page"].url
```

I don't want to call back out into the template engine to have it render a sub-template for these blocks for performance reasons, and to keep the layout for the page -- it would be a template that's used nowhere else -- contained in one file.

The Jinja template for the index page has a fragment that looks like this right now.

```jinja
<ul>
    {% for link in page.quick_links %}
    <li><a href="{{ link.block.get_url(link.value) }}"><p>{{ link.value.text }}</p></a></li>
    {% endfor %}
</ul>
```

So if I could override that the `BoundBlock`s for my `QuickLinkBlock` were, say, `QuickLinkBoundBlock`, I'd be able to add a `@property` called `url`, and turn `link.block.get_url(link.value)` into `link.value.url` or similar.

Does this illuminate things? :bulb:

**Comment by gasman** [comment]
OK, thanks for the clarification!

I don't think `BoundBlock` is the right place for this behaviour: there are lots of places where the value doesn't get wrapped in a `BoundBlock` in the way you expect (for example, accessing a child of a StructBlock gives you a plain unwrapped value), which would leave people wondering why their `url` property isn't available. However, it seems to me that we could make a very similar change to StructBlock, so that instead of returning StructValue instances (which behave as a plain dictionary) it could return a custom object with the additional methods:

```python
class QuickLink(StructValue):
    @property
    def url(self):
        if self.get("external_url"):
            return self["external_url"]
        else:
            return self["page"].url

class QuickLinkBlock(StructBlock):
    page = PageChooserBlock(label=_("page"), required=False)
    external_url = URLBlock(label=_("external URL"), required=False)
    text = CharBlock(label=_("link text"), required=True)

    class Meta:
        value_class = QuickLink
        # there might be a better name than value_class...
```

Does this look like it would do what you need?

**Comment by akx** [comment]
Yeah, I think that would work fine.
Really, anything that'd make the resulting Jinja code something like the obvious

```jinja
<ul>
    {% for link in page.quick_links %}
    <li><a href="{{ link.url }}">{{ link.text }}></a></li>
    {% endfor %}
</ul>
```

(notice the lack of `.value.text` in the link text too)

would be great. :D

**Comment by gasman** [comment]
Thanks! I don't think there's a good way to drop the `.value.text` bit - for most purposes, the extra level of indirection is a good thing, so that you can check 'what type of block is this?' before digging into its properties. Your example is a bit of a special case, as you only have one block type - a `ListField` as proposed in #2048 would solve this nicely though!

I'll close this ticket now, and open a new one for the alternative StructValue approach.

**Pull request closed without merging**
