### PR TITLE
Fixes #1298

### LINKED ISSUE #1298: UI: A long list of children in the explorer results in a gap in the left-hand nav
screen shot 2015-05-14 at 7 01 31 pm

### PR DESCRIPTION
**Pull request by alexgleason**
Moves the background from`.nav-wrapper` to `.nav-wrapper .inner` where it will always be visible. Removes the unnecessary/repetitive background color from `.nav-main .footer`.

### CODE REVIEW

**Comment by davecranwell** [comment]
Thanks for the PR, @alexgleason. From what I can see this causes problems at mobile viewing sizes:

screen shot 2015-09-01 at 16 07 19

Perhaps the background just needs to be on both `.nav-wrapper` _and_ `.nav-wrapper .inner` ?

**Comment by alexgleason** [comment]
@davecranwell Finally tested this, you were right on both those selectors needing the BG color. Will make sure to also check mobile in the future before sending a PR.

**Comment by gasman** [comment]
*bump*

Happy to merge this, @davecranwell?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by davecranwell** [comment]
As far as I can tell this work is also present in #1746, but yes, go ahead.

**Pull request merged**
