### PR TITLE
Updated wagtail admin jQuery to version 2.2.1

### PR DESCRIPTION
**Pull request by nek4life**
Updated the wagtail admin to use the latest version of jQuery. Had another pull request open (#2194) but jQuery has released another version since. I tried to rebase and fix the origin patch, but it ended up being a little confusing due to a conflict so I just made a clean commit off of master since it was an easy patch to begin with.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
:+1:

**Comment by davecranwell** [comment]
Merged in https://github.com/torchbox/wagtail/commit/0a9ae79ba4a0b9816ee1efee0945308487569728

**Comment by tomdyson** [comment]
Thanks, @nek4life!

**Comment by SalahAdDin** [comment]
Here i have a problem with the release candidate:
wagtail - add collection - chromium_048

**Pull request closed without merging**
