### PR TITLE
[Elasticsearch 2] Replaced usage of index_analyzer 

### PR DESCRIPTION
**Pull request by kaedroho**
Resubmission of #2568

index_analyzer has been removed in Elasticsearch 2.0. But the new way works in older versions as well so I think it's worth switching to the new way now.

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_analyzer_mappings

### CODE REVIEW

**Comment by kaedroho** [comment]
@gasman Travis doesn't report any Python 2.7 test failures, neither can I reproduce locally. I also cannot see by looking at the code how a Python 2.7 specific test failure could've occurred.

Could this be remerged?

**Comment by gasman** [comment]
The failure is showing here:
https://travis-ci.org/torchbox/wagtail/jobs/145808149

It seems to be hopping between py27-dj18-sqlite-elasticsearch and py27-dj19-postgres-elasticsearch, so it may be intermittent - but it was happening consistently enough on my machine to run a `git bisect`.

**Comment by gasman** [comment]
Still failing after a rebase (on py27-dj110-mysql-elasticsearch this time): https://travis-ci.org/torchbox/wagtail/builds/145843051 :-(

**Comment by adriaant** [comment]
Having issues using ES > 2.0 that should be fixed in this PR. E.g. 
`raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'Mapping definition for [_partials] has unsupported parameters:  [index_analyzer : edgengram_analyzer]')`
Is this change going to be released soon?

**Comment by gasman** [comment]
@adriaant We can't offer any promises about when ES2 support will be shipped, sorry.

**Comment by adriaant** [comment]
@gasman Well, as long as it does get released at some point ;)

**Comment by kaedroho** [comment]
@gasman It seems to be a bug in Elasticsearch as it occasionally happens with 1.3 and 1.4. But never happens in 1.5+.

**Comment by kaedroho** [comment]
Going to merge this into #2573

**Pull request closed without merging**
