### PR TITLE
Foward kwargs in send_mail

### PR DESCRIPTION
**Pull request by mgd020**
And rename arguments to match django send_mail incase of future updates.

### CODE REVIEW

**Comment by kaedroho** [comment]
Merged in 43f23a600e04e0d478e2d57849782d00bf4c92bf + parent. Thanks!

**Comment by mgd020** [comment]
Do I need to update changelog/release notes or is that done in release-prep?

**Comment by zerolab** [comment]
@mgd020 that was done in e09a56f

**Comment by mgd020** [comment]
Ta! This branch is merged/closed now anyway.

**Pull request closed without merging**
