### PR TITLE
updated abstract form page to call get_context

### PR DESCRIPTION
**Pull request by ser1us**
The class overwrites serve & serve_preview but does not call super. Which means the get_context method is never called on subclasses.

I overwrite the get_context method to add a meta object for the djanog-meta package, but with form pages it's not working because of this.

### CODE REVIEW

**Comment by ser1us** [comment]
I also ran the pep8 --ignore=E501 command, which is telling me that there are some things to fix. Let me know if I should fix the warnings as well :)

**Comment by kaedroho** [comment]
Thanks @ser1us 

I've made a slightly tweaked version here: https://github.com/torchbox/wagtail/compare/master...kaedroho:pr/1429?expand=1

This version removes the ``context.update`` bits, adds a test and fixes the merge conflicts. Does this solve the issue for you?

**Comment by ser1us** [comment]
Hi @kaedroho, yes indeed. That fixes the issue, as long as get_context is called I'm super happy :)

**Comment by gasman** [comment]
Closing in favour of #1541.

**Pull request closed without merging**
