### PR TITLE
Fixing #2519

### PR DESCRIPTION
**Pull request by vincentaudebert**
Stream field background is now lighter grey and icons are white + remove box-shadow to flatten a bit the UI. #2519

### CODE REVIEW

**Comment by tomdyson** [comment]
Thanks @vincentaudebert! Could you please share a screenshot as a comment to this PR?

**Comment by vincentaudebert** [comment]
screen shot 2016-04-28 at 11 14 06 am

Here you go @tomdyson :)

**Comment by gasman** [comment]
Not really keen on this fix, I'm afraid - the streamfield background is a bit _too_ light now (`#fff` on `#777` is insufficient contrast, according to http://webaim.org/resources/contrastchecker/) and this feels like a very dramatic UI change to fix a pretty obscure problem...

**Comment by vincentaudebert** [comment]
All good. I had a quick chat with @joshbarr and we came up with this solution. But I understand your reasons. 
I had played a bit with the explorer border too. I could give it another try even if it wasn't that clear and the explorer menu is pretty messy in terms of CSS.

**Comment by tomdyson** [comment]
Is there an intermediate shade which has enough contrast with the icons / text but is still distinguished from the explorer bar?

**Comment by dirtycoder** [comment]
Why not add a small shadow, using the Wagtail primary color?
This doesn't looks too bad, at least for my taste.

Something like:
```
-webkit-box-shadow: 2px 2px 1px -1px rgba(67,177,176,1);
-moz-box-shadow: 2px 2px 1px -1px rgba(67,177,176,1);
box-shadow: 2px 2px 1px -1px rgba(67,177,176,1);
```

shadow

**Comment by gasman** [comment]
Again I'm not really keen on making a conspicuous design change to fix a bug that very few people will ever notice :-)

What if we add the shadow, but make it semi-transparent white (something like `rgba(255, 255, 255, 0.3)`)? That way, the difference will be hardly noticeable when viewed on the normal white background, but will show up as light grey here.

**Comment by dirtycoder** [comment]
@gasman I think that would be even better. :)
For comparison:

White bg:
shadow

StreamField bg:
shadow2

**Comment by alexgleason** [comment]
I agree with the white background; it's what I initially had in mind as well.

It should have at least a faintly visible border on the top, too, I think.

**Comment by alexgleason** [comment]
screenshot from 2016-04-28 11 45 02

screenshot from 2016-04-28 11 46 26


```css
body.explorer-open .explorer:after {
  content: '';
  width: calc(100% - 2px);
  height: 100%;
  position: absolute;
  top: 0;
  right: 0;
  z-index: -1;
  box-shadow: 0px 0px 2px rgba(255, 255, 255, 0.9);
}
```

Here's my proposed solution.

**Comment by JoshBarr** [comment]
Appreciate all the suggestions here folks.

I think we're on the right track with the lighter streamfield background. But I agree with @gasman that `#777` is too light and fails accessibility. We'll try something in between, like `#555`. 

One of the criticisms I have of the Wagtail UI is that the chrome and colour scheme are very heavy/dark/dense. This isn't conducive to creating an elegant writing environment (see iA's [Writer](https://ia.net/writer/mac/) app!), and we need to do some work to soften the interface. There's a bigger overhaul coming: 

Waggy UI

**Comment by SalahAdDin** [comment]
@JoshBarr Tell us more please.

**Comment by gasman** [comment]
Have applied @alexgleason's fix in 796239b7d991322632da6f9f63fd1ccd172d3b58, as that's the most direct fix to the current issue. Looking forward to the design overhaul though!

**Pull request closed without merging**
