### PR TITLE
Added support for 'exclude_from_explorer' attribute on ModelAdmin class

### PR DESCRIPTION
**Pull request by ababic**
Recreated the branch/PR due to rookie github mistakes with the original. Related to #2757

### CODE REVIEW

**Comment by ababic** [comment]
This is finally passing tests and is ready for review now. Sorry for the long wait.

**Comment by tomdyson** [comment]
Hi @ababic can you please update the docs for this? It's not clear what the attribute does.

**Comment by ababic** [comment]
Hey @tomdyson. I'm happy to add some documentation, but there are currently many attributes/options on the `ModelAdmin` class that aren't properly documented. I wonder if padding out the modeladmin documentation is something that needs tackling in a separate pull? i.e. listing as many attributes as possible and explaining what they do and how they're useful for developers.

**Comment by ababic** [comment]
@tomdyson Also, I was under the impression that a lot of modeladmin's inner workings might be subject to change in the near future now that it's part of wagtail - so as crazy as it might sound, I'm a little bit cautious about documenting every single feature - in case it gets pulled. I feel like it could benefit from a bit of steer from you guys... do you have an idea about what role you want modeladmin to play / which features are important to you / which bits can be replaced with other existing components? Should we perhaps have a discussion about that elsewhere?

**Comment by ababic** [comment]
Hi @tomdyson. Am closing this PR, as it's been superseded by #2878.

**Pull request closed without merging**
