### PR TITLE
Updated jQuery from 1.10.3 to jQuery 2.2.0 in the Wagtail admin

### PR DESCRIPTION
**Pull request by nek4life**
Updated the Wagtail admin to use jQuery 2.2.0 in reference to issue #2186. I tested around in Chrome and Firefox and no errors were thrown in the console while using the admin. I created pages, moved pages, bulk uploaded images, etc... 

I unfortunately do not have IE to test with for the specific iframe issue. I do have experience updating a large application to 2.0 and all the problems I experienced were going from jQuery 1.8 to jQuery 1.9. Pretty much everything else has been seamless going from jQuery 1.9+ to 2.0. If IE6-8 support is not needed I would recommend switching.

### CODE REVIEW

**Comment by davecranwell** [comment]
Excellent, thanks @nek4life! We'll review in due course.

**Comment by tomdyson** [comment]
@davecranwell can you look at this today? Would be good to get it in 1.4. Thanks!

**Comment by davecranwell** [comment]
Tested. Looks fine to me. If there's still time before we merge it might be good to upgrade to 2.2.1 - no sense in being a point release behind if we can avoid it.

**Comment by tomdyson** [comment]
Thanks, Dave. Agreed re the latest version - can you do that, and merge?

**Comment by davecranwell** [comment]
Closed in favour of #2303

**Pull request closed without merging**
