### PR TITLE
Implement `make develop` to ease contributing to wagtail

### PR DESCRIPTION
**Pull request by mvantellingen**
This installs wagtail as editable package in your current python env
and also adds the testing and docs extras

### CODE REVIEW

**Comment by mvantellingen** [comment]
I also think we need to list all targets in the PHONY directive

**Comment by gasman** [comment]
Hi @mvantellingen! I'd be happy to add the makefile option, but I'm not so keen on the idea of advising developers to create Wagtail projects inside the Wagtail source tree. Besides causing problems with version control (we can't rely on them to use the exact name `mysite`...) I think there's a possibility that it could trip up code coverage / linting tools, and it just generally seems like quite a confusing and non-standard way to arrange things.

**Comment by mvantellingen** [comment]
Hi @gasman :-) I actually agree. I copied the https://github.com/mvantellingen/wagtail#getting-started a bit too literally. Any suggestons ?

**Comment by mvantellingen** [comment]
I've decided to keep it simple for now and remove the additional output. In the future it might be helpful to output a link a contributing doc.

Besides that I've also added the ``npm install && npm run build`` command. It's up to the developer to make sure that npm is available (and that a virtualenv is active).

**Comment by gasman** [comment]
Merged, thanks!

**Pull request merged**
