### PR TITLE
Make the bird nod on hover

### PR DESCRIPTION
**Pull request by tomdyson**
and clean up some line endings.

### CODE REVIEW

**Comment by davecranwell** [comment]
You've added the transition to the `:hover` pseudo class, so as soon as the pseudo class is removed (the mouse leaves) the transition property is removed. This means the nod animates into position on mouse enter, but not back out again on mouse leave. If you want the animation to animate in and out, you'll need to move the `transition` to the `img` element a few lines above.

**Comment by tomdyson** [comment]
Thanks, @davecranwell! Updated. This is how it looks now: http://codepen.io/anon/pen/zvgjQO

**Comment by nealtodd** [comment]
Where's the `$ex-parrot: 240deg;` variable? ;)

**Comment by tomdyson** [comment]
@nealtodd yes! Or -120deg for a more realistic tumble: http://codepen.io/anon/pen/MKgLRW

**Comment by gasman** [comment]
We should definitely make use of this variant when we implement #790 :-)

**Comment by gasman** [comment]
On a slightly more mundane note, we should probably add a `wagtail-logo` class on the image and limit the styles to that, so that the spoilsports who have customised it (http://docs.wagtail.io/en/latest/advanced_topics/customisation/branding.html) won't get a jaunty bobbing corporate logo.

**Pull request merged**
