### PR TITLE
Support serialising StreamValue in wagtailapi - fixes #1454

### LINKED ISSUE #1454: API doesn't support StreamField
Here is the traceback:

```
Traceback:
File "/home/lee/Code/cms/venv/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/lee/Code/cms/venv/lib/python3.4/site-packages/wagtail/contrib/wagtailapi/api.py" in wrapper
  69.                 return self.make_response(request, view(request, *args, **kwargs))
File "/home/lee/Code/cms/venv/lib/python3.4/site-packages/wagtail/contrib/wagtailapi/api.py" in make_response
  54.             json.dumps(data, indent=4, cls=WagtailAPIJSONEncoder),
File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/json/__init__.py" in dumps
  237.         **kw).encode(obj)
File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/json/encoder.py" in encode
  194.             chunks = list(chunks)
File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/json/encoder.py" in _iterencode
  422.             yield from _iterencode_dict(o, _current_indent_level)
File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/json/encoder.py" in _iterencode_dict
  396.                 yield from chunks
File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/json/encoder.py" in _iterencode
  429.             o = _default(o)
File "/home/lee/Code/cms/venv/lib/python3.4/site-packages/wagtail/contrib/wagtailapi/api.py" in default
  51.                     return super(WagtailAPIJSONEncoder, self).default(o)
File "/home/lee/Code/cms/venv/lib/python3.4/site-packages/django/core/serializers/json.py" in default
  109.             return super(DjangoJSONEncoder, self).default(o)
File "/home/lee/.pyenv/versions/3.4.2/lib/python3.4/json/encoder.py" in default
  173.         raise TypeError(repr(o) + " is not JSON serializable")

Exception Type: TypeError at /api/v1/pages/6/
Exception Value: [<wagtail.wagtailcore.blocks.stream_block.StreamValue.StreamChild object at 0x7f35564b07b8>, <wagtail.wagtailcore.blocks.stream_block.StreamValue.StreamChild object at 0x7f35564b07f0>, <wagtail.wagtailcore.blocks.stream_block.StreamValue.StreamChild object at 0x7f35564b0208>] is not JSON serializable
```

### PR DESCRIPTION
**Pull request by gasman**

### CODE REVIEW

**Comment by kaedroho** [comment]
How should foreign keys be serialised?

The usual way in Wagtail API is this:

```json
"image": {
    "id": 3,
    "meta": {
        "type": "wagtailimages.Image",
        "detail_url": "http://api.example.com/images/1/"
    }
}
```

Does the streamfield use this format? (and if so, please could you add a test for it)

**Comment by gasman** [comment]
Here I'm just re-using the StreamBlock's own JSON representation, which in this case would just return the integer: `"image": 3`.

I can see the argument for translating the StreamField native value to a more API-friendly JSON format, but that'll be a significantly bigger job requiring design decisions of its own (e.g. how much of it should be implemented in wagtailapi vs wagtailcore.blocks), and I don't think we'd want to hold up Wagtail 1.0 over that (or end up doing a rush job of it).

**Comment by kaedroho** [comment]
I think API stability is important. If we leave the representation as a single integer it should stay that way.

We should either think this though properly now or prevent users from using stream fields until 1.1 as I really want to avoid having to change the API after it has been released.

**Comment by gasman** [comment]
Well, it seems to me that this is exactly the sort of problem that having `/v1/` in the URL is designed to handle :-) I appreciate it's annoying to have to support two versions side by side, though (even if we deal with it under our standard deprecation policy, and only support v1 for the next two releases).

Assuming we won't get the 'ideal' implementation in place for Wagtail 1.0, what would your preferred behaviour be when someone includes a StreamField in `api_fields`? I guess the main options are:

1. Fail (as we do now, but with a more informative error message)
2. Return 'null' for that field, or some other value that clearly signifies "don't use this field, it's not implemented yet"
3. Ship this patch, and version-bump the API to '/v2/' if and when we implement the ideal version
4. Respond as per this patch, but output a warning along the lines of "Accessing a StreamField value over the API is experimental and may change in future releases"

In the interests of doing the most useful thing for end users (and #1454 would indicate that there's demand for this now), I would support option 3 (preferably) or 4. But as you're the lead dev on wagtailapi, I'll let you make that call...

**Comment by kaedroho** [comment]
If I put an image in a streamfield with this patch, will it be output as an integer or will it fail trying to serialise an instance?

If the latter, we could add a serialiser for ``Model`` here https://github.com/torchbox/wagtail/pull/1457/files#diff-40d5c6c68ace6c172f64cb6cab08f764L36 to output the dictionary representation.

**Comment by kaedroho** [comment]
Added another test in: https://github.com/kaedroho/wagtail/commits/fix/streamfield-api

**Pull request merged**
