### PR TITLE
construct_explorer_page_queryset hook for customising explorer page listings

### PR DESCRIPTION
**Pull request by gasman**
Implements #2196.

~~(Incorporates #2215 and #2216)~~

### CODE REVIEW

**Comment by m1kola** [comment]
@gasman, thanks! I think this will be very useful!

At first look everything is ok (of course except https://github.com/torchbox/wagtail/pull/2215#issuecomment-182585036), but I want to look at it again when #2215 and #2216 will be merged.

**Comment by miltontony** [comment]
@gasman Looks good from my side, thanks!

**Comment by gasman** [comment]
Rebased and ready for another look, @m1kola :-)

**Comment by m1kola** [comment]
@gasman, thanks! I think you can merge this PR!

**Comment by kaedroho** [comment]
Merged in d620ce9656da6e5ce535d5621105434481bb9112 +parent. Thanks @gasman and @m1kola!

**Pull request closed without merging**
