### PR TITLE
Fix #3134 - search_garbage_collect command does not work without wagtailsearchpromotions contrib

### LINKED ISSUE #3134: search_garbage_collect management command does not work if wagtailsearchpromotions is not included in INSTALLED_APPS
### Issue Summary

If `wagtailsearchpromotions` is not included in `INSTALLED_APPS` then the `search_garbage_collect` management command fails here: https://github.com/torchbox/wagtail/blob/stable/1.7.x/wagtail/wagtailsearch/models.py#L44 because there is no `editors_picks` field.

### Steps to Reproduce

1. Create a Wagtail site without `wagtail.contrib.wagtailsearchpromotions` in `INSTALLED_APPS`.
2. run the `search_garbage_collect` management command.

Command fails with `django.core.exceptions.FieldError: Cannot resolve keyword 'editors_picks' into field. Choices are: daily_hits, id, query_string`.

### PR DESCRIPTION
**Pull request by ellmetha**
Changes include:
* fixing the FieldError exception that can occur as described in #3134
* adding tests for the "search_garbage_collect" command

### CODE REVIEW

**Comment by gasman** [comment]
Hi @ellmetha - this looks really good, thanks!

Unfortunately I don't think it's possible to modify the `INSTALLED_APPS` list using override_settings - if I revert the fix to wagtailsearch/models.py, `test_garbage_collect_command_works_without_promoted_searches` still passes (indicating that it's still behaving as if wagtailsearchpromotions is installed). As I understand it, override_settings can only affect settings that are read from `django.conf.settings` after override_settings has been called - and, of course, by that time INSTALLED_APPS has already been processed (and thus the `editors_picks` property already exists on the Query model).

Since I can't see a good way of testing the behaviour without wagtailsearchpromotions - other than having a completely separate test runner just for this one test - I'll merge this PR with this test omitted.

**Comment by gasman** [comment]
Merged in 51b4f0f53d93a69f3beaba67e3211cd001ff4087 - thanks!

**Comment by ellmetha** [comment]
Cool! Actually I think that we could've modified the test to properly test how the command behaves without ``wagtailsearchpromotions``. We could've used the Django ``TestCase.available_apps`` attribute. ;-) I can provide a new PR adding the test if you want.

**Comment by gasman** [comment]
The list of "gotchas" at https://docs.djangoproject.com/en/1.10/topics/testing/advanced/#django.test.TransactionTestCase.available_apps makes me think that `available_apps` is going to be more of a liability than a benefit... also, from the description there it sounds like it's only designed to optimise away some database operations, rather than making any deep changes to the relations between apps/models. I think we're fine without a test here, really.

**Comment by ellmetha** [comment]
The ``available_apps`` attribute has an impact on the registry and the models' ``_meta`` fields cache. It turns out that if you remove the wagtailsearchpromotions app from the installed apps (using the ``available_apps`` attribute) the ``editors_picks`` fields won't be returned by the ``Query._meta.get_fields`` method. This would allow to test the desired behaviour.

I note that the test is not needed, though. :smile:

**Pull request closed without merging**
