### PR TITLE
Add page privacy by user/group

### LINKED ISSUE #257: Page View Permission
At this moment, the published wagtail page can be seen by everyone.

How about a way that can limit the people who can see the specific page (people who want to see that page should login and be in specific role) ?

### PR DESCRIPTION
**Pull request by tmiller02**
Fixes #257.

Adds an extra option to the page privacy settings which allows the user to choose which users and user groups can view the live page.

### CODE REVIEW

**Comment by davecranwell** [comment]
I haven't checked how much this overlaps, but this sounds a lot like an existing PR https://github.com/torchbox/wagtail/pull/1076

**Comment by tmiller02** [comment]
Whoops, I completely missed that PR.

**Comment by davecranwell** [comment]
It sounds like your version has added greater granularity, which is still desirable, so perhaps you and @smakinson could pool your efforts? Failing that we could merge one of your two versions of the group-level changes, then ask you to refactor to add only the user-level abilities?

**Comment by smakinson** [comment]
I did not add picking specific users. I figured if someone wants to get that specific they could technically just put a user in his own group. Here is the info: 

https://github.com/smakinson/wagtail/commit/85551df61bc9ce567d1dcb2c6026473b48836268

Perhaps the changes are easily merged if both are desired. I unfortunately do not have the spare time to check right now. @tmiller02 are you able to?

**Comment by tmiller02** [comment]
@smakinson I'd certainly be happy to spend some time looking at this over the course of this week.
@davecranwell I think I might need some clarification on what you mean. In this PR the new privacy option has a single modal dialog for allowing users and groups. Do you mean to split it up into two separate dialogs - one for users and one for groups?

**Comment by Luperi** [comment]
I'm working on the same feature. When will it be released officially? Is there a developer version of wagtail including this feature? Thanks.

**Comment by gasman** [comment]
Hi @Luperi,
There's no developer version with this feature - just this pull request and #1076. The one remaining task that's blocking both PRs is to come up with a general-purpose front-end login system for Wagtail - it needs to be something that works out of the box, but also integrates well with login systems on existing Django sites. See the discussion on https://github.com/torchbox/wagtail/issues/257#issuecomment-144746216. Until this is implemented, there's no estimated timeline for when this will be released.

**Comment by Luperi** [comment]
I've analyzed this pull request, and in my opinion there are some changes to do.

- in wagtailcore/model.py "null=True" in _user_ and _groups_ generates a warning

- in wagtailadmin/forms.py in PageViewRestrictionForm set widget for users and groups to CheckboxSelectMultiple, a more user friendly interface

- @gasman I don't understand why this feature needs a different front-end login system. This feature adds only the possibility to limit the visibility of a page. I've implemented it in this way, and I'm still using the wagtail login.

Thanks.

**Comment by viaregio** [comment]
The milestone "real-soon-now" was added on the 11th of May. Has there been any progress in the last three months?

Django offers the setting LOGIN_URL to customize the URL that is loaded when a login is neccessary. So everyone can choose between the wagtail login page or a custom login page by using this setting. Have i missed something that makes this approach impossible? It would be nice to have a wagtail frontend login mechanism, but it isn't neccessary for this feature.

**Comment by gasman** [comment]
Hi @viaregio - please see my reply at https://github.com/torchbox/wagtail/issues/257#issuecomment-248401768 .

Future commenters: Since we have several issues and PRs open about this feature, I suggest that we continue the discussion at #257 so that we don't have multiple conversations going on in parallel. (Comments specific to the code in this specific PR can of course still be posted here...)

**Comment by gasman** [comment]
Now incorporated into #3071.

**Pull request closed without merging**
