### PR TITLE
Admin GUI fixes

### PR DESCRIPTION
**Pull request by alexgleason**
Here's a list of what's changed:

* Fixes long list of children cause UI gap #1298
* Fixes StreamField hover jitter #1725
* Clicking a RichText block causes it to animate open.
* When the cursor is in a RichText block inside a ListBlock, clicking "Add" would defocus the RichText block first and cause the add to not happen because the button would shoot away from the mouse. This has been improved due to animating RichText blocks open and closed.
* When the cursor is positioned directly over where a button would appear in the Hallo toolbar, then the toolbar appears, the button is solid white until the cursor is moved. This has been fixed.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
:+1:

**Comment by davecranwell** [comment]
Green light from me! Would merging this also automatically merge #1746 which I believe is addressed in this PR too?

**Comment by gasman** [comment]
@davecranwell Do you mean #1745? (If so: yes, it will)

**Comment by davecranwell** [comment]
Great

**Comment by alexgleason** [comment]
Not seeing how this would fix the issue that @gasman linked.

@davecranwell I started this PR working off of a few other fixes that hadn't been merged yet, so you are correct.

**Comment by gasman** [comment]
I meant #1725. Clearly an outbreak of number-blindness going around the office here ;-)

**Comment by gasman** [comment]
Rebased and merged in c813cf1e08241289faca40a02a106238e12aed44. (Couldn't replicate the issue with hovering over a Hallo toolbar button, but happy to take that one on trust :-) ) Thanks!

**Pull request closed without merging**
