### PR TITLE
[WIP] Add account details page

### PR DESCRIPTION
**Pull request by mope**
Add an account details page that allows the user to update their username, email address, first name and last name as specified in #615

### CODE REVIEW

**Comment by davecranwell** [comment]
Assigning to myself for FE review

**Comment by davecranwell** [comment]
* As far as I can tell duplicate username validation isn't working as expected. Usernames are traditionally case insensitive (if ours aren't, they ought to be) but I can change my username to that of another user, just by using a different case e.g "Dave" not "dave". 
* Please can you merge the "Change password" and "Edit account details" screens. It's non-standard to have the password fields separate. I'd expect there to be 3 password fields - one to confirm your old password before making any changes  (a necessary security precaution to prevent hijack of a computer left unattended), and two to set and confirm the new one.

**Comment by gasman** [comment]
> As far as I can tell duplicate username validation isn't working as expected. Usernames are traditionally case insensitive (if ours aren't, they ought to be) but I can change my username to that of another user, just by using a different case e.g "Dave" not "dave".

Usernames are case-sensitive as standard in Django, so this is expected behaviour. FWIW I would be opposed to changing this in Wagtail without very good reason - but either way, it's not a fault of this edit form.

**Comment by SalahAdDin** [comment]
Seens very interesting and useful :D

**Comment by davecranwell** [comment]
Ah ok, didn't realise it was standard. Yeah lets just try and merge the forms. Ignore my validation concerns.

**Comment by davecranwell** [comment]
@mope When do you think you'd be able to look at this?

**Comment by mope** [comment]
@davecranwell I'll see if I can get some time next week to do it

**Comment by mope** [comment]
Binning this in favour of [a simpler implementation](https://github.com/torchbox/wagtail/pull/1277)

**Pull request closed without merging**
