### PR TITLE
Fixes #2790 file handling for custom user add/edit forms/views

### LINKED ISSUE #2790: Custom user image field.
## Context

The custom user model:
```python
class User(AbstractUser):
    avatar = ImageField(
        verbose_name=_('avatar'),
        blank=True,
    )
    organisation = models.CharField(
        verbose_name=_('Organisation'),
        max_length=255,
        blank=True,
    )
```

I am (over)extending this this template (django 1.9):
```html
{% extends "wagtailusers/users/edit.html" %}

{% block extra_fields %}
    {% include "wagtailadmin/shared/field_as_li.html" with field=form.avatar %}
    {% include "wagtailadmin/shared/field_as_li.html" with field=form.organisation %}
{% endblock extra_fields %}
```

The form:
```python
class CustomUserEditForm(UserEditForm):
    avatar = forms.ImageField(
        required=False,
        label=_('Avatar'),
    )
    organisation = forms.CharField(
        required=False,
        label=_('Organisation'),
    )
```

## What I did

I went to settings/users and editing a user, I get a form now showing 2 new fields `avatar` and `organisation`.
I entered a string into the Organisation field and chose a picture for upload for the Avatar field.
I clicked on save.

## What I expected

I expected the organisation and avatar image to be saved on the user model instance that was edited.

## What happened

The organisation was set and saved as expected, however the image never got saved. Clicking on the user again shows the same form with the organisation set and nothing chosen for the avatar field as if I did not choose anything.

## What I tried

I did some research and figured it could have something to do with the form not knowing that it is supposed to handle an image.

References: 
- https://docs.djangoproject.com/en/1.9/ref/forms/api/#testing-for-multipart-forms

So instead of overwriting the `extra_fields` block, I overwrote the whole template telling the form that it contains a multipart encoding.
(The important addition: `enctype="multipart/form-data"`)

Tried this template instead:
```html
{% extends "wagtailadmin/base.html" %}
{% load wagtailimages_tags %}
{% load i18n %}
{% block titletag %}{% trans "Editing" %} {{ user.get_username }}{% endblock %}
{% block content %}

    {% trans "Editing" as editing_str %}
    {% include "wagtailadmin/shared/header.html" with title=editing_str subtitle=user.get_username merged=1 tabbed=1 icon="user" %}

    <ul class="tab-nav merged">
        <li class="active"><a href="#account">{% trans "Account" %}</a></li>
        <li><a href="#roles">{% trans "Roles" %}</a></li>
    </ul>

    <form action="{% url 'wagtailusers_users:edit' user.pk %}" method="POST" enctype="multipart/form-data">
        <div class="tab-content">
            {% csrf_token %}

            <section id="account" class="active nice-padding">
                <ul class="fields">
                    {% block fields %}
                        {% if form.separate_username_field %}
                            {% include "wagtailadmin/shared/field_as_li.html" with field=form.username_field %}
                        {% endif %}
                        {% include "wagtailadmin/shared/field_as_li.html" with field=form.email %}
                        {% include "wagtailadmin/shared/field_as_li.html" with field=form.first_name %}
                        {% include "wagtailadmin/shared/field_as_li.html" with field=form.last_name %}
                        {% block extra_fields %}
                            {% include "wagtailadmin/shared/field_as_li.html" with field=form.avatar %}
                            {% include "wagtailadmin/shared/field_as_li.html" with field=form.organisation %}
                        {% endblock extra_fields %}
                        {% include "wagtailadmin/shared/field_as_li.html" with field=form.password1 %}
                        {% include "wagtailadmin/shared/field_as_li.html" with field=form.password2 %}
                        {% include "wagtailadmin/shared/field_as_li.html" with field=form.is_active %}
                    {% endblock fields %}
                    <li><input type="submit" value="{% trans 'Save' %}" class="button"/></li>
                </ul>
            </section>
            <section id="roles" class="nice-padding">
                <ul class="fields">
                    {% include "wagtailadmin/shared/field_as_li.html" with field=form.is_superuser %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=form.groups %}
                    <li><input type="submit" value="{% trans 'Save' %}" class="button"/></li>
                </ul>
            </section>
        </div>
    </form>
{% endblock %}
```

I checked the request with the debugger: hooking into the `wagtailusers/views/users.py` `edit` view.
```
ipdb> request.FILES
ipdb> <MultiValueDict: {'avatar': [<InMemoryUploadedFile: Carolina.jpg (image/jpeg)>]}>
```
The post headers after sending it:
```
------WebKitFormBoundaryUblppj56HXn14zP2
Content-Disposition: form-data; name="avatar"; filename="Carolina.jpg"
Content-Type: image/jpeg
```

That all looks to me like the problem lies within the wagtail view!
`wagtailusers/views/users.py`
```python
@permission_required(change_user_perm)
def edit(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.method == 'POST':
        form = get_user_edit_form()(request.POST, instance=user)
        if form.is_valid():
            user = form.save()
            messages.success(request, _("User '{0}' updated.").format(user), buttons=[
                messages.button(reverse('wagtailusers_users:edit', args=(user.pk,)), _('Edit'))
            ])
            return redirect('wagtailusers_users:index')
        else:
            messages.error(request, _("The user could not be saved due to errors."))
    else:
        form = get_user_edit_form()(instance=user)

    return render(request, 'wagtailusers/users/edit.html', {
        'user': user,
        'form': form,
    })
```

## Request

None for now, I will try to fix it and send a PR. :D

### PR DESCRIPTION
**Pull request by Eraldo**
This PR fixes the following issue: "Custom user image field." #2790 
I added file handling to support custom user add/edit forms.

### CODE REVIEW

**Comment by gasman** [comment]
Hi @Eraldo - thanks for this!

Instead of adding `enctype="multipart/form-data"` all the time, it would be better to check `{% if form.is_multipart %}`, as we've done in https://github.com/torchbox/wagtail/pull/2420/files - please could you add this?

We also need a test for this (although that'll probably require some updates to the test models / forms in https://github.com/torchbox/wagtail/blob/master/wagtail/tests/customuser/models.py and https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailusers/tests.py).

**Comment by Eraldo** [comment]
Thank you @gasman for your feedback.
I am working on the tests. :)

What is wagtails recommended way to "mock" an image object for the tests?
Since 1.8 I use file-like objects.
Django docs:
```
New in Django 1.8:
The ability to use a file-like object was added.
```
However I am not sure if that would do for wagtail.

Apart from that I am finished integrating your feedback.
Feedback is wanted.

**Comment by gasman** [comment]
Hi @Eraldo,
There's some code for creating a test image at https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/tests/utils.py . I don't think we really need to test with an image file here, though - a plain FileField would work just as well for confirming that file uploads work, and that would simplify the test (see https://github.com/takeflight/wagtail/blob/de0af8769ff1cc11ea7d614ed55a99d48360e9f7/wagtail/wagtailsnippets/tests.py#L179-L188 for example).

**Comment by Eraldo** [comment]
Thank you for the hint and pointers.
I updated the tests accordingly to use "document" as a model attribute (field) instead of an "image".
I ran the test and got some errors. Just some mistakes on my side.
I learned that it is not a good idea to name a user model attribute `document` (especially when using wagtail).
Now everything is going smoothly.
```
Ran 1925 tests in 92.478s
OK (skipped=45, expected failures=2)
```

**Comment by Eraldo** [comment]
@gasman Does that work for you?

**Comment by Eraldo** [comment]
@gasman I tried to rebase my code on the current master since there were some updates on the side of wagtail. Somehow this ticket was closed by accident.
My code is still there.

**Comment by Eraldo** [comment]
Sorry I messed up. Please use the new one: 2799
(based on the current master)

**Pull request closed without merging**
