### PR TITLE
Use QuerySet based search API (and deprecate old search APIs)

### LINKED ISSUE #1: Use django-taggit 0.11's prefetch_related support instead of workaround in wagtailadmin/taggable.py
https://github.com/torchbox/wagtail/blob/70e91d6759e86a0490b478d7f5ae4dafae8bc663/wagtail/wagtailadmin/taggable.py#L51 implements a workaround to the taggit API to allow us to pull in tags on prefetch_related queries. django-taggit 0.11 introduces proper prefetch_related support, so we should use that instead.

(Note that https://github.com/torchbox/django-modelcluster/issues/1 currently blocks us from upgrading to 0.11)

### PR DESCRIPTION
**Pull request by kaedroho**
Also, fixes #1 

Previously, the Page, Image and Document models all had a search method. This pull request deprecates these and replaces them with a QuerySet method instead.

The main advantage of the QuerySet API is filtering is much easier.

Before:
```
images = Image.search(query_string, filters={'uploaded_by_user_id': request.user.id})
```
After:
```
Images = Images.objects.filter(uploaded_by_user=request.user).search(query_string)
```

Any Image, Document or Page QuerySet can be searched like this which should improve code reuse

### CODE REVIEW

**Comment by kaedroho** [comment]
Rebased

**Comment by gasman** [comment]
@kaedroho I think the rebase here may have messed up - it's changing URLs like `wagtailimages:edit` back to `wagtailimages_edit_image`, for example. Please can you investigate / fix?

**Comment by kaedroho** [comment]
Oops, sorry (screwed up a merge conflict resolution during rebase). Fixed now

**Comment by gasman** [comment]
Nice! Have updated the documentation in 94b5975afaa49795bcf87c9155a30f6c20c23e69 - please sanity-check :-)

**Pull request merged**
