### PR TITLE
Getting started docs changes

### PR DESCRIPTION
**Pull request by kaedroho**
Currently, the getting started docs are very focused on technical, Django developers who use a unix-based OS and Vagrant. Theres also a lot of unnecessary detail that just gets in the way. The getting started docs should be focused on getting non-Django developers up and running with Wagtail as quickly as possible.

Heres what I hope to do in this PR:
 - Restructure the getting started docs to move the unnecessary clutter out of the way
 - Add an intro page
 - Take Windows users and non-Django-developers into account
 - Focus less on Vagrant

### CODE REVIEW

**Comment by kaedroho** [comment]
Ready for review,

The getting started docs are still far from amazing but the new structure is definitely an improvement.

**Comment by tomdyson** [comment]
This looks good, Karl. I like the drive towards simplicity. I wonder if we could remove most of the virtualenv stuff - Wagtail doesn't *need* virtualenv and I imagine most Django developers are using it by default.

**Comment by gasman** [comment]
The difficulty with mentioning vs not mentioning virtualenv is that it has a bearing on whether the subsequent `pip install` lines have to be run under `sudo`. If you choose not to mention virtualenv on the basis that it's a developer choice that's external to Wagtail itself, then you're effectively forced to keep up the pretence that you're not using it throughout the rest of the documentation, and artificially add `sudo` to everything :-/

**Comment by tomdyson** [comment]
How about this, in a note block:

"We're assuming that you're installing and running Wagtail in an isolated Python environment, which is more practical than installing packages systemwide, and doesn't require administrator privileges.  (Here's a primer)[link to new page with Karl's virtualenv instructions] if you're not familiar with virtualenvs. If you don't want to use virtual environments, all ``pip install`` lines must be run under sudo, or as an administrator / root user."

**Comment by gasman** [comment]
@tomdyson That works for me!

**Comment by kaedroho** [comment]
Other than the virtualenv stuff (which could be fixed post merge), is everyone happy with the changes here?

**Comment by zerolab** [comment]
:+1: from me.

**Comment by gasman** [comment]
Sorry to be so late to the discussion, but now that we've moved "Trying wagtail" to the start of the docs, the order in which we introduce concepts seems to have gone a bit wonky:

* 'Trying Wagtail': the sentence "If you're happy to use Vagrant..." appears before we've told people what Vagrant is
* 'Installation / Before you start': "Whether you just want to try out the demo site..." - we never mention the demo site again beyond this point
* at the end of paragraph: we're telling non-Vagrant users to "Start from 'Install Python'". In other words, skip the Dependencies section...?

**Pull request merged**
