### PR TITLE
Many changes

### PR DESCRIPTION
**Pull request by SalahAdDin**
Ok, many missing translations and other little fixes :D

### CODE REVIEW

**Comment by kaedroho** [comment]
Thanks @SalahAdDin! Could you squash this into a single commit and call it something like "Spanish translation updates"?

**Comment by SalahAdDin** [comment]
I don't know men, i think so, but, i don't know.
But, i finished translate in Transifex, you cand see then in Transifex :D

**Comment by zerolab** [comment]
Hi @SalahAdDin,

Then, to squash the commits check https://help.github.com/articles/about-git-rebase/. Essentially 

```bash
git fetch upstream
git rebase upstream/master
```

Then `git rebase -i HEAD~7` and pick all, apart from one commit to be squashed.

Hope this helps,
Dan

**Comment by kaedroho** [comment]
@SalahAdDin I assume these are now on Transifex now?

**Comment by SalahAdDin** [comment]
Yes men, all are in Transifex :dancer: :+1:

**Pull request closed without merging**
