### PR TITLE
Refactor pagination into a helper

### PR DESCRIPTION
**Pull request by timheap**
Pagination is done almost exactly the same across all of Wagtail. Moving
the repeated code in to one spot ensures mistakes are not made, and
means that pagination is always done consistently.

There are some locations where the pagination helper has not been used,
as there is no request available or something similar. These instances
are special enough that refactoring them does not make sense at this
point.

### CODE REVIEW

**Comment by kaedroho** [comment]
Could we change the ``paginate`` function slightly so it takes ``items, page_number and per_page``? (and doesn't require request).
 - Makes it useful in places where we don't have the request object (eg https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/taggable.py#L41-L47)
 - Makes it more obvious in view code that the page is coming from the "p" parameter
 - Makes it easier to write tests for

Other than that, looks good to me!

**Comment by timheap** [comment]
One of the main reasons I refactored pagination into a helper is to make it simpler to be consistent, and harder to stray from the normal path. This is why the request is passed in - so the page variable can be extracted from a consistently named GET parameter, defaulting to 1 as expected, and behaving in a sensible manner. While moving the page number to a function argument does make `paginate` usable in one or two more areas, you lose the easily enforced consistency and single function call simplicity of this solution.

I would suggest instead that pagination is dropped from the `TagSearchable.search` method, and the pagination helper is used in its place. Instead of:

```python
p = request.GET.get('p', 1)
documents = Document.search(filters, results_per_page=20, page=p)
```

You would write:

```
documents = paginate(request, Document.search(filters))
```

Clear separation of concerns.

**Comment by kaedroho** [comment]
Not crystal clear separation of concerns as something has to generate a URL with the ``?p=``/``?page=`` in it.

Maybe that could also be done part of the paginate function? (maybe append ``next_page_url`` and ``previous_page_url`` attributes to the ``Page`` object for example).

That might also help clean up code like this (we currently have to reencode all the GET parameters to build a new URL with the "p" parameter appended to it):
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/views/chooser.py#L119
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/templates/wagtailadmin/pages/listing/_pagination.html#L24

**Comment by timheap** [comment]
Alright, I've added a template tag that should help matters: `{% paginate page %}`. It behaves much like the `{% include "wagtailadmin/pages/_pagination.html" %}` include (and even uses that template behind the scenes) but because it is a template tag extra logic can be applied. The page key is configurable now using this tag, and defaults to the same as used in the `wagtail.utils.pagination.paginate` function.

I've converted a few instances of the `{% include "wagtailadmin/shared/pagination_nav.html" %}` include, but I was hesitant to convert more. The way pagination is done through that include means that variables are created in one spot, and used in a template somewhere else, potentially quite a number of `{% includes %}` or `{% extends %}` away from the base template, and I am not confident I would get all of them.

**Comment by davecranwell** [comment]
If possible please can you update the styleguide to use the new tag? Ideally we want the styleguide to be maintained with as much live code as possible.

**Comment by timheap** [comment]
Styleguide has been updated.

**Comment by kaedroho** [comment]
Thanks @timheap and apologies for the delay in re-reviewing

Looks good to me!

**Comment by gasman** [comment]
Rebuilt and merged in #1802.

**Comment by timheap** [comment]
Thanks for rebuilding and merging, @gasman

**Pull request closed without merging**
