### PR TITLE
Webpack fixes

### PR DESCRIPTION
**Pull request by justinvdm**
Some fixes are needed for the changes made in #2275:   - a few dependencies are missing from `package.json`   - webpack aliasing isn't working for the `config` module

### CODE REVIEW

**Comment by kaedroho** [comment]
Thanks @justinvdm!

**Comment by SalahAdDin** [comment]
ok man, but, how can we use webṕack with wagtail resources?

**Comment by kaedroho** [comment]
@SalahAdDin it's only used for creating the js/css bundles that get shipped in each release so this shouldn't be of much interest to site implementors. Webpack is part of Wagtail's gulp-based toolchain which you can find the usage docs for here: http://docs.wagtail.io/en/v1.3.1/contributing/developing.html#compiling-static-assets

**Comment by SalahAdDin** [comment]
Oh, thank's, i saw and error with gulp watch, so, i'll report here.

**Pull request merged**
