### PR TITLE
Willow 0.2 update

### PR DESCRIPTION
**Pull request by kaedroho**
Just released a beta of Willow 0.2. This PR adds support for it into Wagtail.

Will release Willow 0.2 final once everything is tested.

### CODE REVIEW

**Comment by kaedroho** [comment]
Rebased

**Comment by kaedroho** [comment]
Oops, I accidentally forgot to bump the Willow version in tox.ini. Those build errors should be fixed now.

**Comment by zerolab** [comment]
This looks good overall. Ran local build tests for:

- JPEGs/ image quality settings. :+1: 
- the image from #989. :+1: 
- the image from #1084. Unfortunately the issue still persists. :-1: Was hoping that https://github.com/kaedroho/wagtail/commit/332a136d89cb57ab8ca4c3a0a96dc7d07d415724 would fix #1084 as well.

Other than that, Willow 0.2 needs a release before we merge this.

Thanks @kaedroho!

**Comment by tomdyson** [comment]
Thanks for testing, @zerolab. @kaedroho, can you look at #1084?

**Comment by zerolab** [comment]
Had a quick chat with @kaedroho re: #1084.
The simple approach would be to convert non-animated, transparent gifs to png. Animated or non-transparent gifs will retain original format.

Do chip in if you think this is a bad approach (or if there is a better solution).

**Comment by zerolab** [comment]
Re-ran tests locally.
Much better now. Unfortunately the image from #1084 only works correctly when Wand is installed.

So, bump Willow version to 0.2, add doc note to install Wand for full gif support. And :shipit:

**Comment by zerolab** [comment]
After Travis gives green light, of course.

**Pull request merged**
