### PR TITLE
Add system check to confirm that compiled CSS files are present

### LINKED ISSUE #1720: Add system check for missing compiled static files
Currently, attempting to run a Git checkout of Wagtail without running the `npm run build` step results in `UncompressibleFileError`. Add a system check to produce a more informative error message.

### PR DESCRIPTION
**Pull request by gasman**
Fixes #1720. Thanks to Shu Ishida @c16192 for initial development on this feature.

### CODE REVIEW

**Comment by gasman** [comment]
Looks like this is failing on Django 1.7 (only) on Travis because:

* our Travis setup doesn't build the CSS
* Django 1.7 runs system checks on `manage.py test` (and therefore fails this check), but Django 1.8 and above apparently don't
* The unit tests themselves happily run without the CSS and aren't affected by the usual django-compressor error, because our test settings have `COMPRESS_ENABLED = False`

Not sure what the nicest way to fix this is. Options:

* Get Travis to build the CSS (eww)
* Skip the check if `COMPRESS_ENABLED = False`
* Add a new `SKIP_CSS_CHECK` setting
* Add some "is this the test runner?" logic to the system check (isn't there a helper function for this?)
* Wait until we drop Django 1.7 support, and sweep the whole problem under the rug :-)

**Comment by timheap** [comment]
You could also add a `checks.Warning` instead of `checks.Error`. It will fix the issue for Django 1.7, while still warning developers. It wont prevent Django from starting up, unlike `checks.Error`, which is either good or bad depending on how you look at it.

**Comment by gasman** [comment]
@timheap Good idea! Changed to a warning now.

**Comment by kaedroho** [comment]
Merged in 53fb42f275050986072060a550e4fee09ab418f6 Thanks!

**Pull request closed without merging**
