### PR TITLE
don't enforce HTML as template laguage

### PR DESCRIPTION
**Pull request by kakulukia**
sets
HTML_EXTENSION_RE = re.compile(r"(.*)\.[a-z]{3,4}$")

and added option to disable child wrappers

### CODE REVIEW

**Comment by kaedroho** [comment]
Could we swap out the regex stuff altogether and use [os.path.splitext](https://docs.python.org/2/library/os.path.html#os.path.splitext) instead?

**Comment by gasman** [comment]
Thanks @kakulukia!

@kaedroho +1. I was just about to suggest the same thing :-)

**Comment by kakulukia** [comment]
@kaedroho even better :)

**Comment by kakulukia** [comment]
i updated the PR

**Comment by gasman** [comment]
Merged (with test added) in 334bebc55c0e3e4151358b8591e9a4779b0f3ac5 - thanks!

**Pull request closed without merging**
