### PR TITLE
set_url_paths Django 1.10 friendly, add a test

### LINKED ISSUE #3092: Management command set_url_paths broken in Django 1.10
### Issue Summary

`python manage.py set_url_paths` (I don't know what the command is for?) is broken in Django 1.10.

Should the command be removed or fixed?

### Steps to Reproduce

1. `python manage.py help set_url_paths`

### Technical details

* Python version: 3.4
* Django version: 1.10.1
* Wagtail version: 1.6.3

```
$ python manage.py help set_url_paths
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File ".virtualenvs/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File ".virtualenvs/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute
    self.fetch_command(options.args[0]).print_help(self.prog_name, options.args[0])
  File ".virtualenvs/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File ".virtualenvs/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File ".virtualenvs/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File ".virtualenvs/venv/lib/python3.4/site-packages/wagtail/wagtailcore/management/commands/set_url_paths.py", line 3, in <module>
    from django.core.management.base import NoArgsCommand
ImportError: cannot import name 'NoArgsCommand'
```

### PR DESCRIPTION
**Pull request by benjaoming**
Fixes  #3092 

Stumbled upon this bug, I probably don't need the management command, but I guess this kind of fixes it.

### CODE REVIEW

**Comment by benjaoming** [comment]
Can anyone advice on the test failures? They seem unrelated...

**Comment by FFX01** [comment]
Judging by the Travis CI tests, it seems like there is an issue with the search tests specifically. The exception being raised indicates that the certs are missing. Doing some quick googling, I came up with the following:

* http://stackoverflow.com/questions/15586233/python-elastic-search-not-working-pyes-package-issues
* http://elasticsearch-py.readthedocs.io/en/master/exceptions.html
* http://elasticsearch-py.readthedocs.io/en/master/api.html

Take a look at [this test](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailsearch/tests/test_elasticsearch_backend.py#L936).

It looks like it is telling the `ElasticSearchBackend` to use SSL. However, I'm not sure if there is an actual SSL cert to reference. The test isn't failing, the elastic search backend is raising an exception because it cannot find an SSL cert.

Therefore, I don't believe that your changes caused these errors.

**Comment by gasman** [comment]
Hopefully fixed in 162f845e6605191c742ae7aee8b2fd2bc502d0d6 - we weren't specifying an upper bound for the elasticsearch library version to test against, and evidently 5.0.0 has been released in the last few days and become incompatible (or at least, more picky about SSL certificates).

Rebasing on latest master should fix the failures here (although the flake8 failure on the drone build seems to be a legitimate one).

**Comment by benjaoming** [comment]
@FFX01 - thanks for investigating!!

@gasman - I made this PR against 1.6.x because it's a backwards bug fix.. but should I re-target for master instead?

**Comment by gasman** [comment]
@benjaoming Yes, please re-target it on master - the 1.6 branch will only be receiving critical bugfixes (such as security vulnerability and data loss bugs) from now on.

**Pull request closed without merging**
