### PR TITLE
reduce django template control structures inside js code

### PR DESCRIPTION
**Pull request by JoshBarr**
This is an attempt to make the Javascript linter happier about django variables injected into Javascript code, mainly by wrapping them in strings and replacing django control structures with javascript ones. 

There's still a piece of work to be done in `browse.js` and `search.js` to clean up a common dependency, `{% include 'wagtailadmin/chooser/_search_behaviour.js' %}`, which might be better moved into to the modal workflow js?

### CODE REVIEW

**Comment by JoshBarr** [comment]
Sweet, this is passing now. Good to merge!

**Comment by gasman** [comment]
I'm in two minds about this change. On the one hand, it would be good to get our codebase in a linter-friendly state so that we can go ahead with further Javascript development. On the other hand, the need for workarounds like `'true' === 'true'` (not just in the JS code, but in tests too) is raising alarm bells for me.

The problem is that we're side-stepping the question of whether Django template code within Javascript is acceptable according to our coding conventions. For better or worse, the 'modal workflow' component of Wagtail is currently designed around the expectation that you *will* use Django templating to pass server-side information into the JS, whereas the linter is designed on the assumption that the files are pure Javascript. In order to satisfy those two conflicting assumptions, we're forced down the path of using hacks, and I don't think that's going to be sustainable.

I'm certainly not tied to the 'templated JS' approach currently used by modal workflow, and I can see why that pattern would be frowned upon - so I think there are two ways forward here:

* Decide that Django template code in JS is acceptable, and find a way to get the linter to accept or ignore the files in question (possibly by giving them an alternative file extension)

* Decide that Django template code in JS isn't acceptable, and redesign the modal workflow component to not rely on it. For example, rather than the third argument of `render_modal_workflow` being a JS template...

    render_modal_workflow(request, html_template, js_template, context)

...it could be an arbitrary value (typically a dict) which is serialised to JSON and passed as a second argument to the JS function (which would then be defined in a static, non-templated .js file):

    function(modal, userData) {
        ...
    }

Obviously this would be a fair bit more work, but I can see it potentially making the code a lot cleaner - for example, it means that the unit test would be checking for a specific value within the JSON, rather than the presence of a particular snippet of Javascript.

**Comment by tomdyson** [comment]
Should we take @gasman's first option ('get the linter to accept or ignore the files in question') in the short term, so we can accelerate linter-friendliness, and aim to move to the second option ('Decide that Django template code in JS isn't acceptable') in the medium term? If I understand correctly, the latter option makes a React-style UI more feasible for the long term.

**Comment by JoshBarr** [comment]
Hey guys,

Thanks for the feedback. I agree the hacks are not good. Will dispose of the branch, and instead get the linter to ignore those files for now.

I think using django templates within `.js` files isn't ideal for the future. We've been refactoring a big legacy php app (~180k LOC) that did a lot of that, and it doesn't scale well. I'm very much in favour of using JSON to mediate between code that runs in the browser and code that runs on the server.

We've been having some talks about how to implement modal workflows in general, since lots of our projects need them these days. One approach we've used for long-running client-side forms is to define some sort of Hypermedia API of the steps. If we imagine each collection, eg `Documents` or `PrivacySettings` having their own RESTful endpoint within the application and a corresponding client-side component, you could then build modal workflows like this: 

```js
// at http://mysite/admin/client/api/workflows/add-document/step-1
{
    "page": "/client/api/pages/50786df7e9156316fddd5228c4da53af",
    "component": "FileChooser"
    "title": "Add a document",
    "action": "/client/api/workflows/add-document/step-2",
    "data": {
            "valid_types": ["docx", "pdf", "txt"],
            "document_api" "/client/api/documents"
   }
}

// at http://mysite/admin/client/api/workflows/add-document/step-2
{
    "component": "ConfirmModal",
    "action": "/client/api/workflows/add-document/step-3"
},

// etc etc...
```

Each `component` would map to a React component or client-side view. We might need a JS module loader to determine if that component was loaded in the browser.

It's definitely not a small task, though it would be pretty awesome.
* move business logic from django views to some sort of store/collection/model class that's easy to wrap in a RESTful endpoint (with django-rest-framework or similar)
* re-write all the current modal workflows as client-side components. 
* drink a hard-earned and well-deserved pint.

**Pull request closed without merging**
