### PR TITLE
Add docs on committing code

### PR DESCRIPTION
**Pull request by timheap**
Inspiration and flow from Django's `internals/contributing/committing-code` docs

### CODE REVIEW

**Comment by davecranwell** [comment]
Brilliant! Will try following this later today.

**Comment by davecranwell** [comment]
These instructions work a treat, all up to the last steps where `git branch -d pr/xxxx` returns:
```
error: The branch 'pr/2206' is not fully merged.
If you are sure you want to delete it, run 'git branch -D pr/2206'.
```

For completeness, I think there should also be a note about closing PRs manually, once merged, and referring to the commit where merge occurred. I understand this isn't necessary when the PR uses the "Fixed: #[whatever]" syntax, but many don't.

**Comment by timheap** [comment]
I'll amend the documentation to mention that, good catch.

**Comment by m1kola** [comment]
Thanks, @timheap! It's really helpful!

**Pull request merged**
