### PR TITLE
Added a delete Button on the User page #2371

### PR DESCRIPTION
**Pull request by hamsterbacke23**
Hello I am new to Django / Wagtail,
and had a go at adding that delete-button on the user page.
Not entirely sure yet about the permissions...

### CODE REVIEW

**Comment by SableWalnut** [comment]
I was under the impression it was intentional that the only way to 'delete' a user was to make them inactive. Things would get tricky in relation to page revisions if a user is suddenly deleted.

**Comment by hamsterbacke23** [comment]
I see...
As I understood from #2371, deleting a user was no problem, may be I am wrong.

**Comment by gasman** [comment]
Yep, the `user` field on page revisions is nullable (and set to `on_delete=models.SET_NULL`), so deleting the user will just make their revisions 'anonymous' - which is valid at the model level. (We probably ought to test that this gets rendered sensibly on views, but that's a separate issue...)

Hopefully the same is true on any other models that have the concept of being owned by a user, but someone ought to double-check that :-)

(Interesting point about deactivation though - if this isn't what the `is_active` flag is designed for, then what *is* it for? :-) However, I think we can take our lead from django-admin here - django-admin doesn't take any measures to block the 'delete' action in favour of deactivation, so neither should we.)

**Comment by gasman** [comment]
Thanks @hamsterbacke23! We've received several other PRs that implement this, and I've chosen to go with #2523 as it's the most complete - you'll still get a credit in the release though :-)

**Comment by hamsterbacke23** [comment]
Ok thanks!

**Pull request closed without merging**
