### PR TITLE
Hidden field

### PR DESCRIPTION
**Pull request by nimasmi**
This adds a new abstract base class `AbstractHideableFormField`, subclassing `AbstractFormField`.

It has an extra field `is_hidden`, with some validation to prevent silly combinations (such as being set to hidden and required, but with no default value).

Then in `wagtailforms.forms.FormBuilder.formfields` there's a new check for the `is_hidden` attribute, which will cause the widget to be `HiddenInput`, rather than the default.

### CODE REVIEW

**Comment by gasman** [comment]
Implementing 'is hidden' as a flag that modifies any existing field type seems like an overly heavyweight and counter-intuitive way of doing things. Why not just add 'hidden field' to the list of available field types?

**Comment by nimasmi** [comment]
Short answer is I can't remember the use case, as it was October, but your suggestion makes sense.

**Comment by nimasmi** [comment]
I remember spotting this in code, and having reacquainted myself with its use case, after posting the above. It was to do with different validation types, e.g. validating a date vs an integer vs an email address.

**Comment by gasman** [comment]
Why do we need validation on a field the user can't edit (aside from in-browser hacking), though?

**Comment by nimasmi** [comment]
In-browser hacking.

**Comment by gasman** [comment]
If the field content is so sensitive to tampering that we have to guard against users doing that, we probably shouldn't be entrusting it to the user's browser as a hidden field in the first place...

**Pull request closed without merging**
