### PR TITLE
A couple of fixes to get_willow_image

### PR DESCRIPTION
**Pull request by kaedroho**

### CODE REVIEW

**Comment by kaedroho** [comment]
Ready for review

**Comment by kaedroho** [comment]
Just investigating some ``ResourceWarning``s that are now popping up...

**Comment by kaedroho** [comment]
``ResourceWarning`` fixed. Now ready for review!

**Comment by chrxr** [comment]
Hi @timheap, do you have time to review this?
Thanks!

**Comment by timheap** [comment]
:+1: Looks good to me

**Comment by kaedroho** [comment]
Thanks @timheap!

**Pull request merged**
