### PR TITLE
Call Page.unpublish() on each page when unpublishing queryset Fixes #745

### LINKED ISSUE #745: PageQuerySet.unpublish doesn't call page_unpublished signal
This may cause issues with pages not being purged from the cache. This method is only currently used in Wagtail to unpublish pages after copying them (which don't get their page_published signal fired anyway).

I suggest we remove this method and add a ``keep_live`` attribute to the ``Page.copy`` method which when set to false, will not publish the copied pages in the first place.

### PR DESCRIPTION
**Pull request by kaedroho**

### CODE REVIEW

**Comment by zerolab** [comment]
Needs unit tests

**Comment by kaedroho** [comment]
Could we deprecate this method instead?

**Comment by gasman** [comment]
Any particular reason you're thinking of deprecating it? Seems like a fairly useful and uncontroversial thing to be part of the queryset API to me...

**Comment by gasman** [comment]
Superseded by #1934

**Pull request closed without merging**
